### ISSUE TITLE
Perf dialect

### ISSUE THREAD

**Issue by rengolin** [plaidml/tpp-mlir#100]
With the new runner, we need to time the execution of the kernel only, but because the runner calls the JIT compiler, we can't separate the compilation from the execution, and the preparation of tensors from the kernel. But if we had a simple dialect that allows us to start/stop a timer and collect some statistics, we could have that in the input IR (or even add it as a pass), and then we wouldn't need any callbacks, etc.

We'll need a set of ops like:
* `%t = perf.start_timer: perf.timer_t` for some definition of `timer_t` (could be a unique integer)
* `%delta = perf.stop_timer(%t): f64` for the delta from a specific timer, closes the timer (ie. can't take another stop, `%t` is dead)
* `perf.push(%list: memref<1000xf64>, %delta: f64): void` for adding the current delta to a list of results
* `%mean = perf.mean(%list: memref<1000xf64>): f64` for the mean of those 1000 values
* `%dev = perf.stdev(%list: memref<1000xf64>): f64` for the standard deviation of those 1000 values

And a simple runtime implementation for those, calling `std::chrono` or something.

If we get this right, this could be a simple dialect that could easily be upstreamed to MLIR directly without much effort.

**Comment by chelini** [comment]
Indeed would be nice to have.

**Comment by adam-smnk** [comment]
Summary:
- perf dialect added
- perf lowering passes added:
-- `perf.bench` to loops
-- other perf ops to function calls - some have native MLIR implementation, timing related logic requires runtime support
- our benchmarks now use perf dialect for the main benchmarking loop
