### ISSUE TITLE
Parallelization of SCF loops

### ISSUE THREAD

**Issue by KavithaTipturMadhu** [plaidml/tpp-mlir#110]
Parallelize the SCF for loops into SCF  parallel loops either using Nicolas' parallelization technique or by adding static analysis to figure out the dependences across SCF for loops and convert them appropriately into scf parallel ops.

**Comment by chelini** [comment]
https://discourse.llvm.org/t/rfc-primitive-ops-add-broadcastop-to-linalg/66313/10?u=chelini

**Comment by chelini** [comment]
@KavithaTipturMadhu worth tracking this ^^ specifically `gml_st.parallel`.
