### ISSUE TITLE
FP16 vs BF16 tests

### ISSUE THREAD

**Issue by KavithaTipturMadhu** [plaidml/tpp-mlir#127]
Add test to compare that tensors generated by lowering types using tpp_identity (fp16 to bf16) are almost equal using check dialect.

**Comment by rengolin** [comment]
@KavithaTipturMadhu have you added the tests you wanted?

**Comment by KavithaTipturMadhu** [comment]
I haven't added them yet, will work on this soon.

**Comment by rengolin** [comment]
This probably isn't relevant right now, since we don't support `fp16` anyway, and would need to implement `fp16` into our runtime and dialects to make it work.

If/when we add support for `fp16` we will add those tests anyway.
