### ISSUE TITLE
Tensor cast folding, resulting in linalg not matching to tpp

### ISSUE THREAD

**Issue by KavithaTipturMadhu** [plaidml/tpp-mlir#133]
https://github.com/plaidml/tpp-sandbox/pull/115/files In the tests committed, when tensor is generated instead of memref and casted from unranked to ranked memref, the cast operator folds, resulting in subsequent linalg.generic op not matching any tpps.

**Comment by rengolin** [comment]
@adam-smnk @KavithaTipturMadhu is this still a problem in the default pipeline?

**Comment by rengolin** [comment]
Those tests have changed considerably and this isn't an issue anymore.
