### ISSUE TITLE
Map linalg to BF16 TPP ops

### ISSUE THREAD

**Issue by rengolin** [plaidml/tpp-mlir#148]
Now that we have TPP ops working with BF16, we need to lower BF16 tensor types to VNNI packing.

This should be a matter of packing the tensors at the right time, moving the VNNI elements contiguously, and adding a dimension into the `linalg.generic`, making sure we can traverse them with the right maps (compatible with VNNI) and then recognise those maps to TPP VNNI calls.

@KavithaTipturMadhu, as discussed earlier.

**Comment by KavithaTipturMadhu** [comment]
VNNI Dialect added in https://github.com/plaidml/tpp-sandbox/pull/172

**Comment by KavithaTipturMadhu** [comment]
VNNI Dialect extended to memref operands, bufferization added in https://github.com/plaidml/tpp-mlir/pull/181

**Comment by KavithaTipturMadhu** [comment]
https://github.com/plaidml/tpp-mlir/pull/221 Lowers brgemm and matmul to tpp through VNNI dialect.
