### ISSUE TITLE
TPP equations support

### ISSUE THREAD

**Issue by rengolin** [plaidml/tpp-mlir#152]
Add support for TPP equations, examples here:
https://github.com/libxsmm/libxsmm/tree/main/samples/equation

The main point of equations is that you can `dispatch` multiple instructions at once, and the JIT compiler will optimize (fuse, vectorize) based on the sequence of ops, not individually. This can bring significant speedups.

Today we do fusion (ex. GEMM+RELU) but that's a special case. We want to move to a generic case, where we can fuse anything that the implementation knows how to handle. We'd need information from the library on what it can fuse, though.

As an example, in pseudo-IR, we currently do:
```
// Original IR
%a, %b ...
%c = linalg.identity()
linalg.generic(%a, %b, %c) { %m = arith.mul(%an, %bk); arith.add(%m, %cn) }
linalg.generic(%c) { arith.maxf(%i, 0) }

// TPP IR
%c = tensor.empty()
scf.for (%n) {
  scf.for(%k) {
    scf.for(%n) {
      %c = tpp.brgemm_with_init_and_relu(%a, %b, %c)
} } }

// XSMM IR
%c = tensor.empty()
%call = xsmm.dispatch(brgemm_with_init_and_relu)
scf.for (%m) {
  scf.for(%k) {
    scf.for(%n) {
      %c = xsmm.invoke(%call, %m, %k, %n)
} } }
```

But that `dispatch` is a special version that only works for that fusion. 

With equations, we'd have a generic mechanism for many other patterns:
```
// Original IR
%a, %b ...
%c = linalg.identity()
linalg.generic(%a, %b, %c) { %m = arith.mul(%an, %bk); %cn = arith.sub(%m, %cn); %cn = arith.add(%m, 42); }

// TPP IR
%c = tensor.empty()
scf.for (%n) {
  scf.for(%k) {
    scf.for(%n) {
      tpp.group {
        %x = tpp.mul(...)
        %y = tpp.sub(...)
        %c = tpp.add(...)
      }
} } }

// XSMM IR - Today
%c = tensor.empty()
%mcall = xsmm.dispatch(mul)
%scall = xsmm.dispatch(sub)
%acall = xsmm.dispatch(add)
scf.for (%m) {
  scf.for(%k) {
    scf.for(%n) {
      %x = xsmm.invoke(%mcall, ...)
      %y = xsmm.invoke(%scall, ...)
      %c = xsmm.invoke(%acall, ...)
} } }

// XSMM IR - With Equations
%c = tensor.empty()
%call = xsmm.dispatch(mul, sub, add)
scf.for (%m) {
  scf.for(%k) {
    scf.for(%n) {
      %c = xsmm.invoke(%call, %m, %k, %n)
} } }
```

The shape of the dialect is still undefined, as we gather more ideas on how to do that, but the basic idea is to group the fused ops and issue a single dispatch, while controlling which fused op refers to what original op, in sequence.

**Comment by egeor** [comment]
Just for more clarity I would write the XSMM IR more like:
'''
     %z = xsmm.invoke(%call, %a, %b, %c)
'''
One of the nuances of the Matrix Equations in the current implementation of LIBXSMM is that they are restricted to equation trees, i.e. only a single output at the head of the equation-tree VS a more generic graph of operations (the tree structure simpifies the logic for the backend optimizations, register allocation etc.) . For more details on this see Section 4 of the longer TPP paper (https://arxiv.org/pdf/2104.05755.pdf)

**Comment by rengolin** [comment]
Ah, yes, apologies, I put the `tcp.group` on the wrong IR level (XSMM instead of TPP). Description corrected, thanks!

**Comment by rengolin** [comment]
We may not get to do these soon, so I'll close it in order to avoid issue pollution. If we want to do this in the future, we can reopen.
