### ISSUE TITLE
Add a resnet-like test/benchmark

### ISSUE THREAD

**Issue by rengolin** [plaidml/tpp-mlir#190]
We need to break Resnet down into blocks and add those blocks as individual tests.

Later layers of a Resnet 50 have the "bottleneck", which replaces two `3x3` convolutions with `{ 1x1, 3x3, 1x1 }`. This allows us to test BRGEMMs for the `1x1` and GEMMs for the `3x3`. We can also use the first convolution to test a `7x7` filter.

The tasks in this issue are:
1. Get the first bottleneck into a self-contained MLIR file in `test/Benchmarks`
   1. Add `tpp-opt` checks for the appropriate TPP operations
2. Create fake dense weights as global memrefs and leave only the inputs as parameters
   1. Add `tpp-run` checks for output
3. Add the MLIR file as a benchmark in `benchmarks`

Repeat for the  `7x7` layer. We may want to also add the fully-connected layer at the end

Once benchmarks are working with XSMM calls, implement an XSMM function that reproduces a bottleneck for comparison with the MLIR file.

**Comment by rengolin** [comment]
@nhasabni

**Comment by nhasabni** [comment]
Reference PR #239

**Comment by rengolin** [comment]
Is this complete with the merge of #239?

**Comment by nhasabni** [comment]
> Is this complete with the merge of #239?

I think 7x7 conv block is not complete yet. Otherwise, bottleneck block is complete.

**Comment by rengolin** [comment]
With 1x1 and 3x3 done on both output and execution, I think the 7x7 should be fine with just `tpp-opt` output calling TPP ops after the expected pack and we're done, then.

**Comment by rengolin** [comment]
Also, the C++ implementation in XSMM will be done using the libxsmm-dnn repository and is covered by a separate issue (#197)

**Comment by nhasabni** [comment]
Sounds good then. Feel free to close the issue then.

**Comment by rengolin** [comment]
Ok, let's focus on other benchmarks before increasing the scope of this one.
