### ISSUE TITLE
Move `mlp-all.mlir` from `TPP` to `Benchmarks`

### ISSUE THREAD

**Issue by rengolin** [plaidml/tpp-mlir#191]
We already have an MLP file in `test/Benchmarks` but that's a single layer and the one in `TPP` has four.

This issue is about moving the four-layer one into the benchmark folder and improving the MLP C++ benchmark to cope with multiple layers.

Should be done after #175 is finished, so we only do it once.

**Comment by adam-smnk** [comment]
This issue is duplicated and further refined by #250
