### ISSUE TITLE
Add Multi-Head-Attention test/benchmark

### ISSUE THREAD

**Issue by rengolin** [plaidml/tpp-mlir#192]
To test our transforms in complex code we should use the most common target nowadays: Attention layer.

This is a picture of the attention layer (and it's larger cousin):
![attention](https://user-images.githubusercontent.com/1040968/204798480-df7e4137-1805-41b2-a45c-f9cc28bdbbf4.png)
_Extracted from the third link below._

Here are some links to understand what it means:
https://paperswithcode.com/method/multi-head-attention
https://towardsdatascience.com/transformers-explained-visually-part-3-multi-head-attention-deep-dive-1c1ff1024853
https://medium.com/@smitasasindran/12-attention-mechanisms-multihead-attention-958041a35553

You can generate the whole thing with [Keras](https://keras.io/api/layers/attention_layers/multi_head_attention/) or [PyTorch](https://pytorch.org/docs/stable/generated/torch.nn.MultiheadAttention.html), then export to MLIR.

**Comment by nhasabni** [comment]
@rengolin I can take this one (since marked as high-priority), if no one is working on it and no other issue.

**Comment by rengolin** [comment]
@nhasabni any progress on this? We should have more building blocks before we get more entire models in the repo, so that we can progress with the compiler work without needing to look at the entire thing.

**Comment by nhasabni** [comment]
Addressed in #342
