### ISSUE TITLE
Add multi-core support for tile calls

### ISSUE THREAD

**Issue by rengolin** [plaidml/tpp-mlir#193]
After blocking and tiling, we end up with a nested loop of TPP calls to GEMM/BRGEMM. Those can run in parallel, but currently, we don't do that.

A simple idea is to insert [OpenMP](https://mlir.llvm.org/docs/Dialects/OpenMPDialect/) ops to parallelise the execution of the outer loops once we know what the tiles look like. Another option is to use `scp.parallel` or `scp.foreach_thread` and make sure that propagates correctly to the back-end.

Later, when we have some end-to-end execution with IREE or OpenXLA, we can use their runtime to run in parallel.

**Comment by chelini** [comment]
You can actually generate scf.parallel if you map after bufferization: https://github.com/plaidml/tpp-mlir/commit/303b46503ecc0ee98606632201bbba45c9a2094a

**Comment by chelini** [comment]
I was lazy and I did not do that when we map to conv. But should be an easy change.

**Comment by rengolin** [comment]
This is the same as #110
