### ISSUE TITLE
Add default schedule for transform

### ISSUE THREAD

**Issue by chelini** [plaidml/tpp-mlir#205]
Provide a pass that instantiate the transform operations. For example, for a convolution operation we may want to use the following default optimization:
```
transform.sequence failures(propagate) {
  ^bb0(%arg1: !pdl.operation):
    %0 = transform.structured.match ops{["linalg.conv_2d_nhwc_hwcf"]} in %arg1
    %1 = transform.structured.generalize %0
    %2 = transform.structured.interchange %1 { iterator_interchange = [ 0, 1, 4, 5, 2, 3, 6 ] }
    transform.structured.map_conv_to_matmul %2
}
```

**Comment by rengolin** [comment]
We stopped working on transforms for now. Not sure what will be the state when we do restart work, so I'll close this for now and we can start again once we do.
