### ISSUE TITLE
Create a pre-pass in `tpp-run` with the default pipeline

### ISSUE THREAD

**Issue by rengolin** [plaidml/tpp-mlir#234]
`tpp-run` needs MLIR to be in a certain state (post-TPP), adds the main function, then lowers the rest to LLVM Dialect (as a post-pass) and executes.

We need to change it to accept any MLIR file from "linalg on tensors" to "scf with xsmm calls on memrefs" (not LLVM Dialect), so that we can run any file through it.

The first step is to create a pre-pass, just like the post-pass, that lowers the IR to the required format. This will, in turn, be our default pipeline (which can be reproduced by `tpp-opt` by hand).

The main goals of this issue are:
* Change all execution tests to run on `tpp-run` instead of `mlir-cpu-runner`
* Add new tests to pass increasingly lower IR forms to make sure the pipeline works
* Be able to add the main file (perhaps optional) to IR from any level (up to XSMM, not LLVM).

**Comment by adam-smnk** [comment]
Note to future self.
Added basic collection of default passes (`-default-tpp-passes`) to lower TPP to core low-level dialects.

Next steps:
- create test cases with progressive lowering and mixed levels of IR
- move from mlir-cpu-runner to tpp-run
- try adding more specialized passes e.g., packing and tiling with some default values, brgemm stuff etc.

**Comment by rengolin** [comment]
We need to get the convs too. We should add at least one benchmark with a 1x1 conv to test that.
