### ISSUE TITLE
Add `expect-sane` operation to `check` dialect

### ISSUE THREAD

**Issue by rengolin** [plaidml/tpp-mlir#235]
We could add a `check-sane` (or some better name) to the `check` dialect, that would return true if the tensor/memref doesn't have NaNs or Infs. We could even add a `delta` to make sure the normalization happened correctly (`-1 < x < 1`).

@KavithaTipturMadhu

**Comment by KavithaTipturMadhu** [comment]
I am not sure I understand the normalization part, why would we need a delta to check normalization of floating point?

**Comment by rengolin** [comment]
The point was to check if the values are all between `-1 ` and `1` after normalization, as a "sanity" check, but just realised it can be done with `check_almost_eq(tensor, 0.0, 1.0)`. I think #241 fixes this issue completely.
