### ISSUE TITLE
TPP Semantics and Mapping

### ISSUE THREAD

**Issue by chelini** [plaidml/tpp-mlir#243]
We need to have a more strict sematics for TPP, most of the bugs we have when mapping to TPP is that it is unclear the semantics or the sematics changed and the mapping not . For example, let's consider the relu. The op we have in tpp is:

` tpp.relu out(%1: memref<2x2xf32>)` 

It takes a single operand `%1` and does a in-place relu. However, we allows to map to relu semantically different op like the below generic

``` 
#map = affine_map<(d0, d1) -> (d0, d1)>
func.func @relu_mapping(%arg0: memref<10x10xf32>, %arg1: memref<10x10xf32>) {
  %c0 = arith.constant 0.0 : f32
  linalg.generic {indexing_maps = [#map, #map], iterator_types = ["parallel", "parallel"]} ins(%arg1: memref<10x10xf32>) outs(%arg0: memref<10x10xf32>) {
    ^bb0(%in : f32, %out : f32):
      %0 = arith.maxf %in, %c0 : f32
      linalg.yield %0 : f32
  }
  return
}
```

In this case the op is doing: `%arg1 = relu(%arg0)`. This if we map the above op to tpp we miss the copy sematics in `arg1` and if downstream ops uses `arg1` we are broken.

Similar for the tpp.add, we have:

`tpp.add ins(%1 : memref<2x2xf32>) out(%2: memref<2x2xf32>)`

It takes a single input operand `%1` and a single output operand `%2`. But again we map the following generic op.

```
#map = affine_map<(d0) -> (d0)>

!tensor_t  = tensor<2048xf32> // N,H,W,Ic

func.func @entry(%input1 : !tensor_t,
                %input2 : !tensor_t) -> !tensor_t {
    %1487 = tensor.empty() : !tensor_t
    %1488 = linalg.generic {
            indexing_maps = [#map, #map, #map], 
            iterator_types = ["parallel"]
        }
        ins(%input1, %input2 : !tensor_t,  !tensor_t) 
        outs(%1487 : !tensor_t) {
            ^bb0(%in1: f32, %in2: f32, %out: f32):
                %x = arith.addf %in1, %in2 : f32
                linalg.yield %x : f32
    } -> !tensor_t

    return %1488 : !tensor_t
}

```

The sematics in the above op is `%1487 = %input1 + %input2`. This we miss again the fact that we are copying into `%1487`.

Solution:
1. Make tpp.add 2 inputs 1 output and effectively implement C = A + B
2. Fix the mapping and keep A += B

**Comment by KavithaTipturMadhu** [comment]
Listing down the options as we discussed @chelini :
1. We could lower to the form a+=b if there's only one ins operand and one outs operand in linalg generic. The downside of this is that we miss tppfication opportunities for when the linalg op is in the form c=a+b instead of a+=b. Also, if we rely on fusion at tpp level instead of linalg, this might lead to missed fusion opportunities.
2.  We could lower to the form a+=b in case of two operand operations, and c=a+b in case of 3 operand operations. This could significantly increase the complexity of matching and lowering. 
3.  We could force lower all the ops to the form c = a+b, this introduces new buffers which is avoidable in many cases.

**Comment by alheinecke** [comment]
Let's start bottom up: Our TPP implementation in LIBXSMM does comply with SSA for eltwise (only GEMM has with beta = 1 the += on C). 

TPPs are specified to do:

- Out = Unary( In0 )
- Out = Binary( In0, In1 );
- Out = Ternary( In0, In1, In2 );

For Performance reasons, TPP just guarantee to work also when there is full / partial aliasing such that ReLU can happen in place. 

I personally feel that 3. from @KavithaTipturMadhu  list is the best way to go. It gives us functionality right now. Then we can do optimizations on top to get rid of tmps. 
 
- optimize tmps and leverage the aliasing option
- combine / fuse TPPs (equations / GEMMs); experience from manually writing TPP code tells us that > 95% of the tmps go away here for free

**Comment by nhasabni** [comment]
Why not lower `c=a+b` into `c = a; c += b` to leverage in-place update semantics of TPP add? So just to be clear:

- linalg `c = a + b` maps to `c = a; c += b` in TPP
- linalg `c += b` maps to `c += b` in TPP

That way we don't need temporaries, right? Or am I missing something?

BTW, do we know how many ADDs in a standard DL model (such as ResNet) are in-place? Just curious.

**Comment by alheinecke** [comment]
TPP defines add  `c = a + b` so we should also make sure we can use it

**Comment by nhasabni** [comment]
> TPP defines add `c = a + b` so we should also make sure we can use it and there is no `c+=b` TPP

`tpp.add` accepts only 2 operands right? So it is performing `c+=b`. Or am I missing something?

**Comment by alheinecke** [comment]
`tpp.add` it not aligned with the TPP defintion. Add should be a binary TPP. so in the backend the current  `tpp.add` is mapped to `c = c + b`. When we touch we should align with the actual backend and only the GEMM TPP has optional `+=` semantics (when beta is non-zero).

**Comment by alheinecke** [comment]
https://github.com/libxsmm/libxsmm/blob/main/documentation/libxsmm_tpp.md

**Comment by nhasabni** [comment]
> `tpp.add` it not aligned with the TPP defintion. Add should be a binary TPP. so in the backend the current `tpp.add` is mapped to `c = c + b`. When we touch we should align with the actual backend and only the GEMM TPP has optional `+=` semantics (when beta is non-zero).

Got it. Thanks. Makes sense.

**Comment by chelini** [comment]
> Let's start bottom up: Our TPP implementation in LIBXSMM does comply with SSA for eltwise (only GEMM has with beta = 1 the += on C).
> 
> TPPs are specified to do:
> 
> * Out = Unary( In0 )
> * Out = Binary( In0, In1 );
> * Out = Ternary( In0, In1, In2 );
> 
> For Performance reasons, TPP just guarantee to work also when there is full / partial aliasing such that ReLU can happen in place.
> 
> I personally feel that 3. from @KavithaTipturMadhu list is the best way to go. It gives us functionality right now. Then we can do optimizations on top to get rid of tmps.
> 
> * optimize tmps and leverage the aliasing option
> * combine / fuse TPPs (equations / GEMMs); experience from manually writing TPP code tells us that > 95% of the tmps go away here for free

This looks like a tensor-based specification but the tpp dialect we currently have works on memref. Let's discuss this during the next meeting.

**Comment by rengolin** [comment]
> This looks like a tensor-based specification but the tpp dialect we currently have works on memref.

I don't think this is a tensor vs memref question, just value vs pointer semantics. Linalg uses pointer semantics on tensors, and it should be trivial to do value semantics on memrefs (alloc + pointer operand).

It's generally easier to lower value semantics to pointer semantics and elide useless copies than untangle pointer semantics while performing complex transforms. That's why tensors come before memrefs. 

Leaving left-over copies (and allocas) should be tractable for later cleanup passes, if we need to. It's generally easier to do a cleanup pass after-the-fact than try to consider all possible cases during all other unrelated transforms.

**Comment by chelini** [comment]
Addressed in: https://github.com/plaidml/tpp-mlir/commit/85dff85d03bd7498c41957e7e1a246ca099b8dc5
