### ISSUE TITLE
Add an `MLP` model generated directly from `Python` to `Benchmarks`

### ISSUE THREAD

**Issue by adam-smnk** [plaidml/tpp-mlir#250]
Test cases that use automatically generated MLIR should be added in order to start testing how the `tpp-mlir` infrastructure handles code coming from existing MLIR generators (`PyTorch`, `Keras` etc.).

A small MLP model is a good candidate to start moving `Benchmarks` in this direction:
- pick any of the Python frameworks capable of generating MLIR
- generate MLIR code from an MLP model - a simple four-layer one should be sufficient
- create an MLP C++ baseline implementation - existing C++ benchmarks might be a good starting point, it might need some extension

Supersedes #191

**Comment by rengolin** [comment]
Fixed by #400
