### ISSUE TITLE
Add MobileNet end-to-end model as a model

### ISSUE THREAD

**Issue by nhasabni** [plaidml/tpp-mlir#254]
Import TensorFlow MobileNet model into Linalg MLIR and ensure that the MLIR code can be optimized using `tpp-opt` and can run using `tpp-run`. Add appropriate CHECKs to verify TPP lowerings, XSMM calls, and also correctness of output.

**Comment by rengolin** [comment]
We don't worry too much about mobilenet for now, so having an example to tpp/xsmm should be enough for now.
