### ISSUE TITLE
F32 matmul results invalid

### ISSUE THREAD

**Issue by KavithaTipturMadhu** [plaidml/tpp-mlir#275]
```  func.func @entry()->tensor<128x512xf32>{
  %c1 = arith.constant 1.0 : f32
  %c0 = arith.constant 0.0 : f32
  %arg0Val = tensor.empty():tensor<128x256xf32>
  %arg0 = linalg.fill ins(%c1:f32) outs(%arg0Val:tensor<128x256xf32>)-> tensor<128x256xf32>
  %arg1Val = tensor.empty():tensor<256x512xf32>
  %arg1 = linalg.fill ins(%c1:f32) outs(%arg1Val:tensor<256x512xf32>)-> tensor<256x512xf32>
  %1 = tensor.empty(): tensor<128x512xf32>
  %2 = linalg.matmul ins(%arg0, %arg1: tensor<128x256xf32>, tensor<256x512xf32>) outs(%1: tensor<128x512xf32>) -> tensor<128x512xf32>
  %constant = arith.constant 256.0:f32
  %buf = tensor.empty():tensor<128x512xf32>
  %constantBuf = linalg.fill ins(%constant:f32) outs(%buf:tensor<128x512xf32>)->tensor<128x512xf32>
  //check.expect_almost_eq(%2, %constantBuf, %constant):tensor<128x512xf32>, tensor<128x512xf32>, f32
  return %2 : tensor<128x512xf32>
}
```
I compiled the above mlir using the flags  ``` -empty-tensor-to-alloc-tensor -one-shot-bufferize="bufferize-function-boundaries allow-return-allocs function-boundary-type-conversion=identity-layout-map" -drop-equivalent-buffer-results -finalizing-bufferize --linalg-ext-to-loops --convert-check-to-loops --convert-vnni-to-tpp --convert-linalg-to-tpp -canonicalize -convert-tpp-to-xsmm -convert-xsmm-to-func -canonicalize -convert-linalg-to-loops -convert-vector-to-scf -convert-scf-to-cf -expand-strided-metadata -lower-affine  -arith-expand -reconcile-unrealized-casts``` When run using tpp-run, the printed results show nans and invalid results instead of 256 everywhere as expected.

**Comment by chelini** [comment]
Can you please create a test case?

**Comment by KavithaTipturMadhu** [comment]
Test case created in https://github.com/plaidml/tpp-mlir/pull/276

**Comment by KavithaTipturMadhu** [comment]
Looks like some local changes were the reason the tests were failing, i see correct results now.

**Comment by rengolin** [comment]
Can you add a dense matrix to compare to instead of printing? To make sure the bug is in the printing and not in the codegen (which would be more likely I think).

**Comment by rengolin** [comment]
> I see correct results on some runs whereas other runs fail with abort.

This is not good. Once you fixed the leak, did that improve the pass rate?

**Comment by KavithaTipturMadhu** [comment]
> > I see correct results on some runs whereas other runs fail with abort.
> 
> This is not good. Once you fixed the leak, did that improve the pass rate?

The failure was not due to leaks locally, and these runs are failing on and off. There doesn't seem to be a pattern.
