### ISSUE TITLE
Missing value dependency between `perf.bench` `args` and `perf.yield`

### ISSUE THREAD

**Issue by adam-smnk** [plaidml/tpp-mlir#277]
`perf.bench` op does not capture correctly the relation between the op's `args` and their reuse within the region.
The `args` should model the same data relation and reuse as `scf.for` op's `iter_args`.

However, currently this link is missing and it allows folders to freely remove operations that use `args` inputs.
As an example, the following test fails:
```
// RUN: tpp-opt %s -canonicalize -convert-perf-to-loops | FileCheck %s

// CHECK: @bench_canonicalize({{.*}}, %[[k:.*]]: i64)
func.func @bench_canonicalize(%n: i64, %k: i64) -> (i64) {
  // CHECK-DAG: %[[output:.*]] = arith.constant 0 : i64
  // CHECK: %[[deltas:.*]] = memref.alloc
  %size = arith.index_cast %n : i64 to index
  %deltas = memref.alloc(%size) : memref<?xf64>
  %output = arith.constant 0 : i64

  // CHECK: %[[res:.*]] = scf.for %[[i:.*]] = {{.*}}iter_args(%[[iarg0:.*]] = %[[output]]) -> (i64) {
  // CHECK:   %[[timer:.*]] = perf.start_timer
  // CHECK:   %[[sum:.*]] = arith.addi %[[iarg0]], %[[k]]
  // CHECK:   %[[delta:.*]] = perf.stop_timer(%[[timer]] {{.*}})
  // CHECK:   memref.store %[[delta]], %[[deltas]][%[[i]]]
  // CHECK:   scf.yield %[[sum]]
  // CHECK: }
  %res = perf.bench (%n, %deltas : memref<?xf64>) args(%output : i64) {
    %sum = arith.addi %output, %k : i64
    perf.yield %sum : i64
  } -> i64

  memref.dealloc %deltas : memref<?xf64>

  // CHECK: return %[[res]]
  return %res : i64
}
```

Just by running `tpp-opt -canonicalize`, the `arith.addi` get folded away as it fits `a + 0` pattern.
The missing dependency between the initial `%output` and the fact that its value gets updated through `perf.yield` allows this folding to happen.

The goal of this issue is to somehow prevent this erroneous folding from happening.

**Comment by rengolin** [comment]
Can you join the need for `perf.sink` and `perf.yield` and make the latter with the semantics of the former, so that we always yield the computation value (in addition to whatever else)? If DCE still removes it after the loop, we can put the consuming function outside of the loop and avoid the fiddling with the timer order.

**Comment by adam-smnk** [comment]
> Can you join the need for `perf.sink` and `perf.yield` and make the latter with the semantics of the former, so that we always yield the computation value (in addition to whatever else)? If DCE still removes it after the loop, we can put the consuming function outside of the loop and avoid the fiddling with the timer order.

It might be one way to force the behavior but I believe this usage dependency should be coming directly from the `perf.bench` definition. @chelini suggested that it should be possible to capture the dependency semantic by adding `RegionBranchOpInterface` to the `perf.bench`. Looking at the docs, it seems promising so I'll try that out.

Also, the current `args` definition is a bit vague, it should probably just fully mimic `src.for iter_args` for simplicity and clarity.
