### ISSUE TITLE
Split the default passes into sub-passes

### ISSUE THREAD

**Issue by rengolin** [plaidml/tpp-mlir#280]
To be able to include our passes on other frameworks, we need to combine them with their existing pipelines. Since our our default passes span from high to low level, we need to break them down so we can insert the right ones at the right levels.

We also need to have generic passes that are also executed by other frameworks (like bufferization, canonicalization, etc) so that those don't get exposed to frameworks, but do get called by the [default pipeline](https://github.com/plaidml/tpp-mlir/blob/main/lib/TPP/DefaultTppPasses.cpp#L62).

A quick breakdown of the blocks:
* **Transforms**: This should not be part of the exported methods, as it may interfere with their own transforms.
* **Conv2GEMM/packing**: These are the core high-level passes.
* **Bufferization**: Common to all frameworks, separator for high/low-level passes (tensor/memref)
* **Linalg-to-TPP/BRGEMM**: These are our core mid-level passes.
* **Lower Check dialect**: What about Perf?
* **TPP-to-XSMM**: These are our core low-level passes, preceded by LICM/loop fusion
* **Postprocessing**: This should not be part of the exported methods, we keep them locally.

In addition, IREE's own pipeline seems to run canonicalizaiton and CSE after every major pass, we probably should do the same, at least after every "level" on our default pipeline, but not include them on the exported functions.

### Concrete proposal

Local methods:
* `createTransformPass()`: Runs interpreter and local cleanup. This can be exported later, if we get transforms working across.
* `createCleanupPass()`: Runs canon/CSE, to be inserted locally after each pass on the default pipeline
* `createBufferizationPass()`: Runs one-shot and other bufferization passes, like other frameworks
* `createPostprocessingPass()`: Runs buffer helpers, at the end
* `createLocalDialectsLoweringPass()`: Runs lowering for both check and perf

Exported methods:
* `createTPPMappingPasses()`: High-level, conv-2-gemm / packing (blocking/tiling), etc.
* `createTPPConversionPasses()`: Mid-level, gemm/brgemm, tpp calls, etc.
* `createTPPLoweringPasses()`: Low-level, TPP-to-XSMM (or loops), LICM, loop-fusion, etc.

And the order of the default pipeline becomes, without anything else in the main function:
* `createTransformPass()`
* `createCleanupPass()`
* **`createTPPMappingPasses()`**
* `createCleanupPass()`
* `createBufferizationPass()`
* **`createTPPConversionPasses()`**
* `createCleanupPass()`
* **`createTPPLoweringPasses()`**
* `createCleanupPass()`
* `createLocalDialectsLoweringPass()`
* `createPostprocessingPass()`

@adam-smnk

**Comment by rengolin** [comment]
The feedback on pipeline integration is [positive](https://discourse.llvm.org/t/proposal-pass-manager-builder-for-mlir/67982). We should start separating our passes from generic passes and spread them as they would be in an upstream framework, as described in this issue.

On #263, we should try to add just our exported passes to IREE's pipeline and adjust the knobs to match both our internal cases and IREE.

Once we're happy with the results, we should start working on the pass manager builder.

**Comment by adam-smnk** [comment]
Resolved by #356
