### ISSUE TITLE
Add ResNet50 end-to-end model

### ISSUE THREAD

**Issue by nhasabni** [plaidml/tpp-mlir#281]
Import TensorFlow Resnet50 model into Linalg MLIR and ensure that the MLIR code can be optimized using tpp-opt and can run using tpp-run. Add appropriate CHECKs to verify TPP lowerings, XSMM calls, and also correctness of output.

**Comment by rengolin** [comment]
I was thinking we should move entire models into repos like https://github.com/plaidml/tpp-iree because each "entire model" will be relative to what the front-end can generate, and that will be different for XLA/IREE, PyTorch, etc.

**Comment by nhasabni** [comment]
PR #284 addresses the model part.

**Comment by rengolin** [comment]
For now, having just the model is good enough, as we're not testing performance on convolution models. If later we decide to work on them again, we can reopen this issue.
