### ISSUE TITLE
Add a pass to pack/unpack constant tensors at compile time (weights)

### ISSUE THREAD

**Issue by rengolin** [plaidml/tpp-mlir#291]
Any constant tensor should be packed / unpacked at compile time and saved back on the IR as its packed version.

This should be a pass after pack propagation and should replace a pack operation of a constant tensor to another constant tensor with the packed shape.

Dynamic tensors (input arguments) cannot be packed at compile time, so remain as a pack op.

There could be some cases where we can't yet propagate the right packing throughout the model, so we may retain a few pack/unpack operations around, but ultimately, we need to get them all.

Because this needs propagation to work, and propagation is a hard problem, this issue is just about adding the pass, not making sure every pack is made constant. Later, when the propagation is working as intended, we can create a new issue that will take case of the remaining cases.

@chelini @alheinecke

**Comment by chelini** [comment]
Done in: https://github.com/plaidml/tpp-mlir/commit/31225c988ea4f7c9775f52c42d705e4da0cc03ea
