### ISSUE TITLE
Add `pack-matmul` and `pack-vnni` to the default pipeline

### ISSUE THREAD

**Issue by rengolin** [plaidml/tpp-mlir#361]
When creating the MLP generator (#360), I noticed the matmuls weren't being packed on `tpp-opt --default-tpp-passes`. It seems those passes aren't on our standard pass.

We need to add them to the default pipeline so that we can automatically optimise MLP without the need of running `tpp-opt` twice.

We may need to pass the tile sizes to the pass, so this could be an extra option on `tpp-opt` and `tpp-run`?

@adam-smnk

**Comment by adam-smnk** [comment]
For the sizes, I'd hardcode 32 for `pack-matmul` as the default for now and expose an option to pass custom values when needed.
We could also add `pack-conv2D*` passes.
