### ISSUE TITLE
Move all passes to the default pipeline

### ISSUE THREAD

**Issue by rengolin** [plaidml/tpp-mlir#369]
We have a number of passes that are not connected to the default pipeline. While the default pipeline was created after some of those passes, it's about time we make sure all of our work can be used directly without magic flags. We also need to demonstrate all our passes interoperate with all our other passes in a non-destructive way.

The work here is to:
1. Go through every pass that is not in the default pipeline yet.
2. Find the best place for it to be in the default pipeline and move it there.
3. Discuss appropriate flags and options and how to pas this from `tpp-opt` and `tpp-run`.
4. Add/move execution test to the Integration directory, using `tpp-run` and compare outputs.

There may be a few passes that do not belong in the default pipeline. For example, the transform pass, or #367. For those cases, we need a clear and reasonable reason not to include and document it in the header file (so that we don't come back here again).

@chelini @adam-smnk @KavithaTipturMadhu

**Comment by adam-smnk** [comment]
> > `element-wise-fusion` which is no longer needed by any other pass and can be left out of the default pipeline for now.
> 
> #400 shows that this might not be true on all cases.

Fair point. It can be still beneficial to fuse linalg ops we don't lower to TPP.
I'll have to see where it could be added in the pipeline. Maybe in the `post-processing` or a separate `post-opt` pass as this fusion doesn't really fit to any of the existing pipeline stages.

**Comment by adam-smnk** [comment]
TODO: add `combine-tpp` to the default pipeline when the pass itself is fixed
The pass be added at the end of `TppConversionPass` after all other ops have already been lowered to TPP.

**Comment by rengolin** [comment]
Is there anything left over from the previous passes? If not, I guess we can close this for now.
