### ISSUE TITLE
Refactor TPP matchers to scale with the number of ops we'll soon add

### ISSUE THREAD

**Issue by rengolin** [plaidml/tpp-mlir#371]
Right now we only have a few ops: identity, matmul, add, relu. The helper methods that we use to match them aren't always trivial and are repeatedly tested until something matches (or not).

We already have issues with those, for example:
* Identity is a generic op, that can mean no-op, copy, broadcast, reduce, transpose, etc. but we only really implement broadcast and copy.
* ReLU can come from different patterns and we're having issues with its detection (#370, #355, #227, etc).

Soon, we'll be adding a lot more operations, and this convoluted matching strategy won't scale. We need a better one.

The most important things are:
* Be able to detect **all** variants for **all** ops (from single and multi ops, matmul, generic, etc).
* Optimally only check each property once for a group of possible ops (iterative refining strategy).
* Translate operation semantics (ex. from table-gen) to matching rules.

If we can find a way to organise the operations into sets and find structured intersecting properties, we may get away with some decision tree. 

Libxsmm already groups those ops into `unary`, `binary`, `ternary`, `gemm`, etc. so we should be able to do the same. However, it also has cross-boundary properties and flags (ex. broadcast on binary ops), so we may have to repeat _some_ checks, hopefully the cheap ones.

Another thing to consider is what we match against.

On ReLU, we can match multiple "zeros" (float constant, dense constant, dense global, zero fill) into a `linalg.generic`, so when replacing the op, we may have to clean it in different ways, or run DCE at the end of every match. But more importantly, we'll need to traverse back the IR in different ways, depending on the pattern we're matching.

On GEMM, we can match `linalg.matmul` (for 2D cases) or `linalg.generic` with `{ arith.mulf + arith.addf }` inside, and they can be replaced with each other when packing / unpacking. We need to be aware of the patterns here, to replace TPP ops that we know the provenance.

Finally, there's matching a `linalg.generic` with multiple instructions inside. Some tensor passes can fuse bias add and ReLU to the end of a matmul to block & tile all of them together. The end result is the perfectly nested `par(par(red(mul+add) + add + max)` sequence that we can just lower to a TPP BRGEMM operation. But for that, we need to look into the nested `linalg.generic` and "match" the right operations.

Not to mention support for TPP equations (#152) that will need this matching blocks with multiple instructions, but that's in the future.

**Comment by chelini** [comment]
We now use structural and access matchers: https://github.com/plaidml/tpp-mlir/commit/418733ad0d741e5babea931ed4c42291362dd46e

**Comment by rengolin** [comment]
Yes, this is the "scale up" issue, where we can use the matchers to go through a large number of linalg ops, not just one.

**Comment by rengolin** [comment]
Since we don't have the TPP dialect any more, this issue has moved upstream to "scale linalg named ops graph/op matchers" and should be tracked upstream.
