### ISSUE TITLE
Cannot lower 1d tpp.identity to XSMM

### ISSUE THREAD

**Issue by chelini** [plaidml/tpp-mlir#375]
To reproduce:
```
func.func @main(%arg0: memref<8xf32, strided<[1]>>, %arg1: memref<8xf32, strided<[1]>>) {
  tpp.identity ins(%arg0 : memref<8xf32, strided<[1]>>) out(%arg1 : memref<8xf32, strided<[1]>>)
  return
}
```
The tpp.identity does not lower to xsmm.

**Comment by rengolin** [comment]
Is this due to some missing BROADCAST flag in the runtime?

**Comment by chelini** [comment]
> 

No, we bail out if the output is not 2d: https://github.com/plaidml/tpp-mlir/blob/4f9666a2598310abb4c21dc61db97f150715cb5a/lib/TPP/ConvertTppToXsmm.cpp#L372

**Comment by rengolin** [comment]
This issue should be unnecessary, now that we'll retire `tpp.identity` and will have specific `zero`, `copy` and `broadcast` unary ops.

**Comment by chelini** [comment]
This comes from old decisions to lower 1d and 2d tile operations. Should we just lower 2d tile operations?

**Comment by chelini** [comment]
We can close, but we would need to rework tpp mapping to avoid 1d ops. We can simplify loop lowering and xsmm if we allow 2d tiles only. Do we all agree on the direction?

**Comment by chelini** [comment]
See: https://github.com/plaidml/tpp-mlir/pull/553/commits/0b97a55b3cb108bde13de1dcf0a12b68359d392c
