### ISSUE TITLE
MLIRBench - improve kernel result deallocation

### ISSUE THREAD

**Issue by adam-smnk** [plaidml/tpp-mlir#379]
Current MLIRBench kernel wrapped generation examines entry function signature and if it explicitly returns a memref, a deallocation op is generate to prevent memory leaks.

This approach does not always work when the input kernel is at the tensor level. Often returned tensor is automatically converted into a destination-passing memref (last argument is used instead of return) and then no additional memory cleanup is necessary. However, this bufferization behavior is not guaranteed and sometimes the kernel can still return a memref buffer. With current approach, this leads to memory leaks.

This fix this issue, MLIRBench should examine kernel IR after lowering (at least after the default pipeline) to determine whether result buffer deallocation is necessary.

**Comment by rengolin** [comment]
@adam-smnk has this been fixed?

**Comment by adam-smnk** [comment]
Bufferization has improved quite a lot. I don't think we've run for a long time into any problems related to this issue.
The fact that we improved structure of our IR kernels also helped to prevent running into this/similar problems.

But overall, MLIRBench could use some minor improvements in term argument and memory management.
I'd keep it open but put it to low priority.
