### ISSUE TITLE
Propagation through tensor.collapse/expand and tensor.insert/extract.

### ISSUE THREAD

**Issue by chelini** [plaidml/tpp-mlir#381]
It is unclear how to propagate through `tensor.collapse_shape` and `tensor.expand_shape`. This code snippet has been taken from packing a matmul in the MHA model.

```
    %collapsed = tensor.collapse_shape %arg0 [[0, 1], [2]] : tensor<32x8x128xf32> into tensor<256x128xf32>
    %pack_dest = tensor.empty() : tensor<8x4x32x32xf32>
    %pack = tensor.pack %collapsed inner_dims_pos = [0, 1] inner_tiles = [32, 32] into %pack_dest : tensor<256x128xf32> -> tensor<8x4x32x32xf32>
    / * some packed IR */
    %unpack_dest = tensor.empty() : tensor<256x128xf32>
    %unpack = tensor.unpack %5 inner_dims_pos = [0, 1] inner_tiles = [32, 32] into %unpack_dest : tensor<8x4x32x32xf32> -> tensor<256x128xf32>
    %expanded = tensor.expand_shape %unpack [[0, 1], [2, 3]] : tensor<256x128xf32> into tensor<32x8x2x64xf32>
```

Possible solution: push `tensor.collapse_shape` and `tensor.expand_shape` at the boundaries before pack/unpack propagation.

**Comment by rengolin** [comment]
> Possible solution: push `tensor.collapse_shape` and `tensor.expand_shape` at the boundaries before pack/unpack propagation.

Interesting. Would this become a propagation on its own? Then we would have `pack + collapse` followed by code and `expand + unpack` at the end for the dynamic case (inputs), and the equivalent constant propagation for the weights and biases.

Alternatively, we could translate those ops into pack/unpack, and propagate those, to reach the same goal.

Whatever is easier at this point, really.

**Comment by chelini** [comment]
> > Possible solution: push `tensor.collapse_shape` and `tensor.expand_shape` at the boundaries before pack/unpack propagation.
> 
> Interesting. Would this become a propagation on its own? Then we would have `pack + collapse` followed by code and `expand + unpack` at the end for the dynamic case (inputs), and the equivalent constant propagation for the weights and biases.
> 
> Alternatively, we could translate those ops into pack/unpack, and propagate those, to reach the same goal.
> 
> Whatever is easier at this point, really.

Yes, would be another propagation. I don't think we can pack or unpack, collapse or expand shape. I mean, how to get the packing information is unclear to me.

**Comment by chelini** [comment]
Here some examples taken from MobileBert:

```
#map11 = affine_map<(d0, d1, d2) -> (d1, d0, d2)>
#map12 = affine_map<(d0, d1, d2) -> (d0, d1, d2)>

func.func @main(%49: tensor<12x4x32x32xf32>, %44: tensor<384x128xf32>) -> tensor<384x32xf32> {
  // I want to sink. 
  %unpack_964 = tensor.unpack %49 inner_dims_pos = [0, 1] inner_tiles = [32, 32] into %44 : tensor<12x4x32x32xf32> -> tensor<384x128xf32>
  %expanded_966 = tensor.expand_shape %unpack_964 [[0], [1, 2]] : tensor<384x128xf32> into tensor<384x4x32xf32>
  %56 = tensor.empty() : tensor<4x384x32xf32>
  %57 = linalg.generic {indexing_maps = [#map11, #map12], iterator_types = ["parallel", "parallel", "parallel"]} ins(%expanded_966 : tensor<384x4x32xf32>) outs(%56 : tensor<4x384x32xf32>) {
    ^bb0(%in: f32, %out: f32):
      linalg.yield %in : f32
  } -> tensor<4x384x32xf32>
  %extracted_slice_968 = tensor.extract_slice %57[0, 0, 0] [1, 384, 32] [1, 1, 1] : tensor<4x384x32xf32> to tensor<384x32xf32>
  return %extracted_slice_968 : tensor<384x32xf32>
}
```

```
%extracted_slice_968 = tensor.extract_slice %57[0, 0, 0] [1, 384, 32] [1, 1, 1] : tensor<4x384x32xf32> to tensor<384x32xf32>
%61 = tensor.empty() : tensor<12x1x32x32xf32>
// I want to bubble up.
%pack_976 = tensor.pack %extracted_slice_968 inner_dims_pos = [0, 1] inner_tiles = [32, 32] into %61 : tensor<384x32xf32> -> tensor<12x1x32x32xf32>
```

```
%76 = tensor.empty() : tensor<384x384xf32>
%83 = some linalg op
// I want to sink.
%unpack_984 = tensor.unpack %83 inner_dims_pos = [0, 1] inner_tiles = [32, 32] into %76 : tensor<12x12x32x32xf32> -> tensor<384x384xf32>
%inserted_slice_990 = tensor.insert_slice %unpack_984 into %inserted_slice_989[768, 0] [384, 384] [1, 1] : tensor<384x384xf32> into tensor<1536x384xf32>
```

@rengolin here some more examples for the packing propagation in tensor.extract and tensor.insert

**Comment by chelini** [comment]
Not relevant anymore. We avoid IRs with these ops. In MHA they are introduced by IREE.
