### ISSUE TITLE
`pack-matmul` - MLP and matmul performance regression

### ISSUE THREAD

**Issue by adam-smnk** [plaidml/tpp-mlir#410]
After introduction of packing to the default pipeline in #380, the canary MLP (`mlp-fp32-1layer-512.mlir`) and matmul (`matmul_64x64x64.mlir`) performance has dropped below reference implementations.
The performance drop is due to `tensor.pack` and `tensor.unpack` operations introduced by `pack-matmul` pass. The extra data movement dominates the total execution cost of these models.

`pack-matmul` is needed in the default pipeline as it sometimes enables other passes. However, the rewriting should not be applied when it is detrimental to the performance.

**Comment by rengolin** [comment]
Thanks Adam, though this isn't technically a performance regression. The performance problems were there, just not stressed in a measurable way.

We need to fix these performance issues ASAP, or everything we do will be hampered by bufferization issues and we'll never converge to a stable performance across all benchmarks.
