### ISSUE TITLE
GPU runner

### ISSUE THREAD

**Issue by rengolin** [plaidml/tpp-mlir#430]
We want to try our passes on Intel GPUs, but we need some special sauce to glue our passes with GPU fiddling to get it offloaded onto devices.

We can start with simple recipes and then move to a unified `tpp-gpu-run` just like our `tpp-run`.

@hfp @adam-smnk

**Comment by adam-smnk** [comment]
CUDA support was added to `tpp-run` in #547.
Vulkan support #573 has been parked for now due to lacking server infrastructure.

Closing this issue as we now have at least one viable path to execute IR on GPU.
Further work will be done in separate issues.
