### ISSUE TITLE
[RFC] tpp.matmul lowerings

### ISSUE THREAD

**Issue by chelini** [plaidml/tpp-mlir#466]
Dear All,
Would like to agree first on the general design of `tpp.matmul` prior to update more than 60+ tests. I think we all agree that `tpp.matmul`  should be a ternary operation (meaning 3 inputs and 1 output). Here how @adam-smnk and I see the lowering:

**Tpp on tensor**
`%d = tpp.matmul (%a: tensor<>, %b: tensor<>, %c: tensor<>) -> tensor<>`

**After bufferization** 
`tpp.matmul ins(%a: memref<>, %b: memref<>, %c: memref<>) outs(%c: memref<>)`
if `d` cannot alias with `c` at tensor level we insert a copy:
```
%alloc = memref.alloc %d
memref.copy %c into %alloc
tpp.matmul ins(%a: memref<>, %b: memref<>, %alloc: memref<>) outs(%alloc: memref<>)
```

**XSMM lowering**
`%dispatch = xsmm.ternary\_dispatch(%lda, %ldb, %ldc, %m, %n, %k, %alpha, %beta)`
`%invoke = xsmm.ternary\_invoke(%a, %b, %c, %c)`

To handle alpha and beta we need to add a custom attribute to tpp.matmul. 
Check if `%c` is zeroed is easier at the tensor level and need to propagate
all the way down to the dispatch. Suggested syntax:

`%d = tpp.matmul (%a: tensor<>, %b: tensor<>, %c: tensor<>) -> tensor<> { beta = 1.0, alpha=1.0 }`
beta and alpha will be `FloatAttr`.

**To LIBXSMM**

```
int matmul\_dispatch(const libxsmm\_datatype dtype, int m, int n, int k,
         int lda, int ldb, int ldc, float alpha, float beta);
void matmul\_invoke(const libxsmm\_datatype dtype, int funcAddr, 
          UnrankedMemRefType<> ptrA,
          UnrankedMemRefType<> ptrB,
          UnrankedMemRefType<> ptrC)
```
Here we have a problem `xsmm.ternary\_invoke` dispatch 4 operands while the LIBXSMM
invokes accept 3 only. We dispatch 4 operands because in the general case %c may not alias with %d, it alias in the case of matmul. We can handle matmul as a special case, discarding the rightmost %c as it is an alias with one operand.

What do you think?

**Comment by alheinecke** [comment]
on LIBXSMM side, we must not lower GEMM not into ternay as gemm has it own dispatch and invoke given transpose, vnni, and alpha, beta flags which are all not valid for ternary. There is no ternary for libxsmm as GEMM is not a strict ternary operation in LIBXSMM. 

I agree with matmul on tensor, we can treat it as ternary: D = A * B + C. 

After bufferization the story is much more complicated:  

- if C was initialed to 0 using unary too right before the GEMM, we should lower to binary operation C = A * B. Later this gets lowered to libxsmm GEMM operation with beta=0; this can be seen a special case of the tpp group thingy.
- If C was filled with some 2d matrix or comes from memory, we should lower to a ternary operation C = A * B + C. Later this gets lowered to libxsmm GEMM operation with beta=1
- when we have a tpp group on tensor, then during bufferization we will get a non-trivial logic to fuse this into the ext_gemm operation such that we don't allocate temp buffers we then need to clean-up later. We might also up for the clean-up later approach, but I feel this is brittle.

**Comment by alheinecke** [comment]
BTW:
https://github.com/libxsmm/libxsmm/blob/main/include/libxsmm_typedefs.h#L364
https://github.com/libxsmm/libxsmm/blob/main/include/libxsmm_typedefs.h#L401
are not real binary and ternary standalone ops. They are for equations only and as we wanted to try how GEMM will work in equations. Nothing we are really using today. It was a quick way to try this for some special cases as we didn't need to introduce 2 new nodes (BRGEMM and GEMM) into the equation implementation... as you see the integration is suboptimal as we have to flatten the GEMM flags and not all cases which we support for the GEMM Op are supported here, e.g. it fix assumes alpha=1 and beta=1.

This will need some refactoring. @hfp, @egeor: perhaps for the 2.0 release we want to just comment these ops and just keep the vanilla matmul which is A and B are normal and non-trans and then we add GEMM/BRGEMM as a graph node in 2.1.

**Comment by rengolin** [comment]
> * if C was initialed to 0 using unary tpp right before the GEMM, we should lower to binary operation C = A * B. Later this gets lowered to libxsmm GEMM operation with beta=0; this can be seen a special case of the tpp group thingy; `tpp.matmul ins(%a: memref<>, %b: memref<>) outs(%c: memref<>)`
> * If C was filled with some 2d matrix or comes from memory, we should lower to a ternary operation C = A * B + C. Later this gets lowered to libxsmm GEMM operation with beta=1, `tpp.matmul ins(%a: memref<>, %b: memref<>, %c: memref<>) outs(%c: memref<>)`

In the presence of `tpp.group`, I'd advise against having two syntax for the same op. If we group at tensor level, we can control the dependencies at memref level without needing pointer analysis.

```
// C = A * B
// FROM
tpp.group {
  %c = tpp.zero() : tensor<>
  %d = tpp.matmul(%a, %b, %c) : tensor<>
}
// TO
tpp.group {
  %c = memref.alloc : memref<>
  tpp.zero ins(%c) outs(%c)
  tpp.matmul ins(%a, %b, %c) outs(%c)
}
// TO
xsmm.matmul(%a, %b, %c, BETA=0)
```

```
// C = arg0 + arg1
// C = A * B + C
// FROM
tpp.group {
  %c = tpp.add(%arg0, %arg1) : tensor<>
  %d = tpp.matmul(%a, %b, %c) : tensor<>
}
// TO
tpp.group {
  %c = memref.alloc : memref<>
  tpp.add ins(%arg0, %arg1) outs(%c)
  tpp.matmul ins(%a, %b, %c) outs(%c)
}
// TO
xsmm.binary(%arg0, %arg1, %c, OP=ADD)
xsmm.matmul(%a, %b, %c, BETA=1)
// OR EVEN
xsmm.brgemm(%a, %b, %c, BETA=1, OP=ADD)
```


> * when we have a tpp group on tensor (e.g. when C is filled with a broadcast value like channel bias), then during bufferization we will get a non-trivial logic to fuse this into the libxsmm EXT_GEMM operation such that we don't allocate temp buffers we then need to clean-up later. We might also up for the clean-up later approach, but I feel this is brittle.

```
// C = (bcast) arg0
// C = A * B + C
// FROM
tpp.group {
  %c = tpp.broadcast(%arg0) : tensor<>
  %d = tpp.matmul(%a, %b, %c) : tensor<>
}
// TO
tpp.group {
  %c = memref.alloc : memref<>
  tpp.broadcast ins(%arg0) outs(%c)
  tpp.matmul ins(%a, %b, %c) outs(%c)
}
// TO
xsmm.unary(%arg0, %c, OP=BCAST)
xsmm.matmul(%a, %b, %c, BETA=1)
// OR EVEN
xsmm.brgemm(%a, %b, %c, BETA=1, BCAST=C)
```

> * libxsmm GEMM only supports alpha=1.0 and beta=0.0/1.0 all other will be implemented (for the time being with unary tpp and EXT_GEMM). Or in other words, I feel the proposed alpha/beta infrastructure is way overkill as we can just have two tpp.matmuls on memref level:
>   beta=1 `tpp.matmul ins(%a: memref<>, %b: memref<>, %c: memref<>) outs(%c: memref<>)`
>   beta=0 `tpp.matmul ins(%a: memref<>, %b: memref<>) outs(%c: memref<>)`

I think it's possible to use `tpp.group` to match both as ternary at that level.

**Comment by chelini** [comment]
> 



> on LIBXSMM side, we must not lower GEMM not into ternay as gemm has its own dispatch and invoke given transpose, vnni, and alpha, beta flags which are all not valid for ternary. There is no matmtul ternary standalone for libxsmm as GEMM is not a strict ternary operation in LIBXSMM.
> 
> I agree with matmul on tensor, we can treat it as ternary: D = A * B + C.
> 
> After bufferization the story is much more complicated:
> 
> * if C was initialed to 0 using unary tpp right before the GEMM, we should lower to binary operation C = A * B. Later this gets lowered to libxsmm GEMM operation with beta=0; this can be seen a special case of the tpp group thingy; `tpp.matmul ins(%a: memref<>, %b: memref<>) outs(%c: memref<>)`
> * If C was filled with some 2d matrix or comes from memory, we should lower to a ternary operation C = A * B + C. Later this gets lowered to libxsmm GEMM operation with beta=1, `tpp.matmul ins(%a: memref<>, %b: memref<>, %c: memref<>) outs(%c: memref<>)`
> * when we have a tpp group on tensor (e.g. when C is filled with a broadcast value like channel bias), then during bufferization we will get a non-trivial logic to fuse this into the libxsmm EXT_GEMM operation such that we don't allocate temp buffers we then need to clean-up later. We might also up for the clean-up later approach, but I feel this is brittle.
> * libxsmm GEMM only supports alpha=1.0 and beta=0.0/1.0 all other will be implemented (for the time being with unary tpp and EXT_GEMM). Or in other words, I feel the proposed alpha/beta infrastructure is way overkill as we can just have two tpp.matmuls on memref level:
>   beta=1 `tpp.matmul ins(%a: memref<>, %b: memref<>, %c: memref<>) outs(%c: memref<>)`
>   beta=0 `tpp.matmul ins(%a: memref<>, %b: memref<>) outs(%c: memref<>)`

Why do we need a special case for GEMM/BRGEMM? If we could reuse the ternary lowering instead of creating a custom `xsmm.matmul` would be great. I assume we can pass alpha, beta and all the other parameters to the dispatch.

**Comment by chelini** [comment]
> > Why do we need a special case for GEMM/BRGEMM? If we could reuse the ternary lowering instead of creating a custom `xsmm.matmul` would be great. I assume we can pass alpha, beta and all the other parameters to the dispatch.
> 
> Matmul/GEMM aren't ternary in libxsmm. They have their own flags that are specific to those ops. We can't just use a ternary to encode it, as the ternary flags are not the same as the gemm flags.

Yes, but I think only the dispatch will look different looking at the LIBXSMM header. The invoke should still be a ternary.

> 
> The TPP dialect arity doesn't have to have any relation to the XSMM dialect or with the libxsmm implementation. But it'd be good if the XSMM dialect could be very close with libxsmm.
> 
> Once we have another implementation (OpenCL? Cuda? SYCL?), we can create a new low-level dialect and match that with the implementation again.

**Comment by alheinecke** [comment]
the invoke is not ternary on the library layer...  also alpha/beta would not be part of dispatch if we ever decide to add them, they would be part of the GEMM invoke. Simply we don't want to JIT for every possible alpha/beta a new code.

**Comment by chelini** [comment]
> the invoke is not ternary on the library layer... also alpha/beta would not be part of dispatch if we ever decide to add them, they would be part of the GEMM invoke. Simply we don't want to JIT for every possible alpha/beta a new code.

I was referring to: https://github.com/plaidml/tpp-mlir/blob/b8b25d5d1f0fc9596d55817a5903f698a83b3e66/include/TPP/Dialect/Xsmm/XsmmOps.td#L93 and company. I was thinking we can reuse these for invoke and have a custom dispatch.

```
%0 = xsmm.matmul.dispatch(/*some gemm specific flags */)
xsmm.ternary matmul(dataType f32, %0, %A %B, %C, %C) // beta = 1
xsmm.binary matmul(dataType f32, %0, %A %B, %C) // beta = 0
```

**Comment by chelini** [comment]
Or we use `BETA_0` in the dispatch and always call the ternary:
`xsmm.ternary matmul(dataType f32, %0, %A %B, %C, %C)`. The only annoying thing is that the last %C should be drop when we generate a call to the runtime or will be unsed.

**Comment by rengolin** [comment]
I don't think we should mix `ternary` and `matmul` as the former is used inside equations, which we will eventually support. Other than small (mostly avoidable) boilerplate, there's no additional cost of having more ops.

**Comment by chelini** [comment]
> I don't think we should mix `ternary` and `matmul` as the former is used inside equations, which we will eventually support. Other than small (mostly avoidable) boilerplate, there's no additional cost of having more ops.

xsmm.ternary in equation? Here we are at xsmm level I don't think we plan to have it in equation, no?

**Comment by chelini** [comment]
We now have custom dispatch and invoke for matmul and brgemm. The next step would be to decide what to do with the quaternary operation we have in XSMM. See: https://github.com/plaidml/tpp-mlir/blob/37358183351a10a1dcee537d45a6630ecf7ca34d/include/TPP/Dialect/Xsmm/XsmmOps.td#L21 This operation was introduced to call fused BRGEMM operations and indeed fused BRGEMM is the only lowering it has (https://github.com/plaidml/tpp-mlir/blob/37358183351a10a1dcee537d45a6630ecf7ca34d/include/TPP/Dialect/Xsmm/XsmmEnum.td#L30). Do we really need quaternary operation @egeor and @alheinecke ? If not should we introduce specific dispatch/invoke as we did for matmul and brgemm? Both the dispatch and the invoke in the runtime are different enough to justify a new op in my opinion:
- runtime dispatch: https://github.com/plaidml/tpp-mlir/blob/37358183351a10a1dcee537d45a6630ecf7ca34d/runtime/XsmmRunnerUtils.cpp#L483
- runtime invoke: https://github.com/plaidml/tpp-mlir/blob/37358183351a10a1dcee537d45a6630ecf7ca34d/runtime/XsmmRunnerUtils.cpp#L437

**Comment by egeor** [comment]
We have no TPP op in the spec per se that is quaternary. In that sense I would say specific dispatch/invoke for the fused brgemm is the way to go.

**Comment by rengolin** [comment]
> We have no TPP op in the spec per se that is quaternary. In that sense I would say specific dispatch/invoke for the fused brgemm is the way to go.

We discussed this yesterday and for now we can just lower `unary`, `binary`, `gemm`, `brgemm` and `brgemm_ext`, re-using code to handle all these operands in static functions inside the runtime. 

We may want to fuse all `gemm`s into one op later, but starting with more ops is generally easier than trying to split functionality of a single op into multiple ones.
