### ISSUE TITLE
[RFC] tpp-pack lowering to tpp-identity

### ISSUE THREAD

**Issue by KavithaTipturMadhu** [plaidml/tpp-mlir#478]
There are two ways we can lower tpp-pack operation to tpp-identity currently:

1. lower directly from tensor-pack operation to tpp-identity operation and bufferize it. This avoids the copies created due to transposes and bufferization. 
2. lower like we do right now into transpose and bufferize as we do and constant fold such that we are left with only one copy of transpose operation that gets lowered into tpp-identity operation.

Which of these two approaches would be better, in your opinion?

**Comment by chelini** [comment]
Thanks! I would prefer option 1. We are moving tpp on tensor so I would expect `tensor.pack` -> `tpp.identity` to be easier to implement. We can prioritize tpp bufferization work and connect all the pieces together.

**Comment by rengolin** [comment]
Agree with @chelini, lowering directly to copies is preferred.

Also, let's get the copies in there first, and then lower to those. We really don't need broadcast support for pack sub-ops.

**Comment by rengolin** [comment]
By copy I mean `tpp.copy` from #414

**Comment by alheinecke** [comment]
BTW, the last time I looked at this, there was linalg.transpose in the pack, which was a no-op... I haven't checked if this gets optimized away in later passes.

**Comment by rengolin** [comment]
> BTW, the last time I looked at this, there was linalg.transpose in the pack, which was a no-op... I haven't checked if this gets optimized away in later passes.

That's the upstream lowering to loops, we should just bypass that and lower to tpp before final lowering to loops.

It's not clear to me what that transpose was doing in the pack, maybe @chelini knows?

**Comment by rengolin** [comment]
> The transpose is necessary when we have permutation on the point loops (aka `inner_dims_pos`).

Isn't `inner_dim_pos` meant for `block transpose` instead?

**Comment by chelini** [comment]
> > The transpose is necessary when we have permutation on the point loops (aka `inner_dims_pos`).
> 
> Isn't `inner_dim_pos` meant for `block transpose` instead?

What do you mean by `block transpose`? Basically when lowering, we emit loop nest and we interchange them based on `outer_dim_perms` and we use the transpose for the point loop if we have `inner_dims_pos`.
