### ISSUE TITLE
CI failing everywhere with libxsmm include errors

### ISSUE THREAD

**Issue by rengolin** [plaidml/tpp-mlir#506]
```
.../tpp/libxsmm/include/libxsmm/libxsmm_rng.c:11:10: fatal error: 'libxsmm.h' file not found
--
  | #include <libxsmm.h>
  | ^~~~~~~~~~~
```

@hfp

**Comment by hfp** [comment]
It is mainly about libxsmm-dnn needs to be ported to revised libxsmm. So far, libxsmm-dnn uses some constructs which are now internal to libxsmm or removed.

**Comment by rengolin** [comment]
Feel free to push a fix if it makes the builds green. And in the future make sure libxsmm updates follow dnn updates as well.

**Comment by hfp** [comment]
PR #507

**Comment by alheinecke** [comment]
please note, the feature development for libxsmm and libxsmm-dnn will continue for the time being in "main_stable" branches. Until "main" and "main_stable" is merged we should use libxsmm-dnn in main_stable branch if we want to run libxsmm-dnn benchmarks and need latest versions or libxsmm-dnn.
