### ISSUE TITLE
[RFC] Broadcast semantics only on `tpp.add`

### ISSUE THREAD

**Issue by rengolin** [plaidml/tpp-mlir#516]
Right now we only have one op that needs broadcast semantics: `tpp.add`. But **all** our unary and binary ops have that trait.

We don't really need it and it's confusing to generate code that has to worry about broadcasting semantics when really there's no need.

We need to move the `BroadcastableShape` trait just for `Tpp_AddOp` and fix the tests, if any.

We'll probably redefine the broadcast semantics with a new op later, but for now, this will do with the least damage.

@chelini @alheinecke

**Comment by chelini** [comment]
I briefly had a look at this. We can easily remove the `BroadcastableShape` interface from all the unary but `tpp.identity`, we have 23 tests that uses this trait in `tpp.identity`. If we drop the interface from the op we need to manually change the benchmarks or avoid mapping to tpp. Possible solutions:
1. If we need an op that does a copy without broadcast we can introduce tpp.copy.
2. Add `tpp.broadcast` op and change the mapping to generate a `tpp.broadcast` + `tpp.identity`. We can preserve the tests as they are without changing them.
2) is better but more long term while 1) is fairly quick.

**Comment by rengolin** [comment]
These were my original findings, too. Either way these three things need to happen in some order. Which order depends more on how they affect the rest, but also internal consistency. 

We don't want to have a temporary broken state, even for a few days.

**Comment by rengolin** [comment]
With @KavithaTipturMadhu working on #290 using `tpp.identity`, we should wait until that work is done to create the new ops (broadcast, copy). They're already covered by #414 so we don't need to add a new issue.
