### ISSUE TITLE
[RFC] DPS or non-DPS for tpp on tensor?

### ISSUE THREAD

**Issue by chelini** [plaidml/tpp-mlir#530]
DPS: Destination passing style: the operation carries the destination tensor on which it may or may not bufferize.

TPP on tensors does not support DPS because DPS looks wired at the tensor level. Tensors are immutable, and passing a "maybe" destination is wired. But DPS works with bufferization, or at least it simplifies the logic. Bufferization can bufferize over the output tensor if there are no other conflicts.

Consider the following example taken from MHA:
```
**%2 = tensor.empty() : tensor<256x128xf32>**
%3 = scf.forall (%arg1, %arg2) = (%c0, %c0) to (%c256, %c128) step (%c32, %c32) shared_outs(%arg3 = **%2**) -> (tensor<256x128xf32>) {
  %extract_slice_3 = /* ... */
  %6 = /* ... */
  **%extracted_slice_4** = tensor.extract_slice **%arg3**[%arg1, %arg2] [32, 32] [1, 1] : tensor<256x128xf32> to tensor<32x32xf32>
  %7 = linalg.generic {
     indexing_maps = [#map2, #map2, #map2], 
     iterator_types = ["parallel", "parallel"]} 
     ins(%6, %extracted_slice_3 : tensor<32x32xf32>, tensor<32x32xf32>) outs(**%extracted_slice_4** : tensor<32x32xf32>) {
      ^bb0(%in: f32, %in_5: f32, %out: f32):
        %8 = arith.addf %in, %in_5 : f32
        linalg.yield %8 : f32
    } -> tensor<32x32xf32>
    scf.forall.in_parallel {
        tensor.parallel_insert_slice %7 into %arg3[%arg1, %arg2] [32, 32] [1, 1] : tensor<32x32xf32> into tensor<256x128xf32>
      }
}
```
`%extracted_slice_4` is the "output tensor" for the addition. If we bufferize, bufferization will _not_ introduce any copy because it can use `%extracted_slice_4` as destination. Let's now convert to TPP, where we don't have DPS.

```
%2 = tensor.empty() : tensor<256x128xf32> // outer most allocation
%3 = scf.forall (%arg1, %arg2) = (%c0, %c0) to (%c256, %c128) step (%c32, %c32) shared_outs(%arg3 = %2) -> (tensor<256x128xf32>) {
  %extract_slice_3 = /* ... */
  %6 = /* ... */
  // Note that compared to the above IR we don't have a "destination" tensor: `extracted_slice_4`. Tpp additiona works on
  // %6 and %extracted_slice_3
  %7 = tpp.add (%6 : tensor<32x32xf32>, %extracted_slice_3 : tensor<32x32xf32>) -> (tensor<32x32xf32>
   scf.forall.in_parallel {
      tensor.parallel_insert_slice %7 into %arg3[%arg1, %arg2] [32, 32] [1, 1] : tensor<32x32xf32> into tensor<256x128xf32>
      }
}
```

If we now bufferize TPP, we need to introduce a copy because we cannot directly write on `extracted_slice_4` (we don't have it in the op anymore as an argument). In the tpp case we need to materialize a subview into the outermost allocation (%alloc_1) and emit a memref.copy to copy the local allocation (%alloc_2). Linalg can avoid the copy (but not the local allocation) because is in DPS style (i.e., carry the "subview" as argument).

```
tpp.add ins(%alloc_2 : memref<32x32xf32>, %subview_3 : memref<32x32xf32, strided<[128, 1], offset: ?>>) outs(%alloc_2 : memref<32x32xf32>)
// subview + copy.
%subview_4 = memref.subview %alloc_1[%arg1, %arg2] [32, 32] [1, 1] : memref<256x128xf32> to memref<32x32xf32, strided<[128, 1], offset: ?>>
memref.copy %alloc_2, %subview_4 : memref<32x32xf32> to memref<32x32xf32, strided<[128, 1], offset: ?>>
```

This case is fairly easy to clean-up, but I wonder if we will have more complex cases, and if we should align TPP to use DPS. Currently we fix-up the copy after bufferization. The pattern to detect is fairly easy here:
```
%big_alloc
for (
 %small_alloc
 use (%small_alloc)
 %subview_big_alloc
 copy %small_alloc into %subview_big_alloc
)
// rewrite to:
%big_alloc
for (
  %subview_big_alloc
  use (%subview_big_alloc)
)
```

After the rewrite the IR, looks like:

```
%alloc_1 = memref.alloc() {alignment = 64 : i64} : memref<256x128xf32>
    scf.forall (%arg1, %arg2) = (0, 0) to (256, 128) step (32, 32) {
      %subview = memref.subview %collapse_shape[%arg1, 0] [32, 128] [1, 1] : memref<256x128xf32> to memref<32x128xf32, strided<[128, 1], offset: ?>>
      %subview_2 = memref.subview %alloc_1[%arg1, %arg2] [32, 32] [1, 1] : memref<256x128xf32> to memref<32x32xf32, strided<[128, 1], offset: ?>>
      tpp.zero ins(%subview_2 : memref<32x32xf32, strided<[128, 1], offset: ?>>) outs(%subview_2 : memref<32x32xf32, strided<[128, 1], offset: ?>>)
      tpp.gemm ins(%subview : memref<32x128xf32, strided<[128, 1], offset: ?>>, %0 : memref<128x32xf32>, %subview_2 : memref<32x32xf32, strided<[128, 1], offset: ?>>) outs(%subview_2 : memref<32x32xf32, strided<[128, 1], offset: ?>>)
      %subview_3 = memref.subview %collapse_shape_0[%arg1, %arg2] [32, 32] [1, 1] : memref<256x128xf32> to memref<32x32xf32, strided<[128, 1], offset: ?>>
      tpp.add ins(%subview_2 : memref<32x32xf32, strided<[128, 1], offset: ?>>, %subview_3 : memref<32x32xf32, strided<[128, 1], offset: ?>>) outs(%subview_2 : memref<32x32xf32, strided<[128, 1], offset: ?>>)
      %subview_4 = memref.subview %alloc_1[%arg1, %arg2] [32, 32] [1, 1] : memref<256x128xf32> to memref<32x32xf32, strided<[128, 1], offset: ?>>
    }
```

Interestingly cleaning up the allocation in the inner loop for linalg would be much harder, as we don't have the explicit copy that connect the inner allocation with the outer one.

```
%alloc_1 = memref.alloc() {alignment = 64 : i64} : memref<256x128xf32>
    scf.forall (%arg1, %arg2) = (0, 0) to (256, 128) step (32, 32) {
      %subview = memref.subview %collapse_shape[%arg1, 0] [32, 128] [1, 1] : memref<256x128xf32> to memref<32x128xf32, strided<[128, 1], offset: ?>>
      **%alloc_2 = memref.alloc() {alignment = 64 : i64} : memref<32x32xf32>**
      linalg.fill ins(%cst : f32) outs(%alloc_2 : memref<32x32xf32>)
      linalg.matmul ins(%subview, %0 : memref<32x128xf32, strided<[128, 1], offset: ?>>, memref<128x32xf32>) outs(%alloc_2 : memref<32x32xf32>)
      %subview_3 = memref.subview %collapse_shape_0[%arg1, %arg2] [32, 32] [1, 1] : memref<256x128xf32> to memref<32x32xf32, strided<[128, 1], offset: ?>>
      %subview_4 = memref.subview %alloc_1[%arg1, %arg2] [32, 32] [1, 1] : memref<256x128xf32> to memref<32x32xf32, strided<[128, 1], offset: ?>>
      linalg.generic {indexing_maps = [#map2, #map2, #map2], iterator_types = ["parallel", "parallel"]} ins(%alloc_2, %subview_3 : memref<32x32xf32>, memref<32x32xf32, strided<[128, 1], offset: ?>>) outs(%subview_4 : memref<32x32xf32, strided<[128, 1], offset: ?>>) {
      ^bb0(%in: f32, %in_5: f32, %out: f32):
        %2 = arith.addf %in, %in_5 : f32
        linalg.yield %2 : f32
      }
      memref.dealloc %alloc_2 : memref<32x32xf32>
    }
```

**Comment by chelini** [comment]
@adam-smnk and @rengolin

**Comment by chelini** [comment]
note that `iree_codegen.ukernel.generic` will use DPS at tensor level, thus if TPP will not be DPS we need to DPS-fy before converting to the ukernel ops.

**Comment by chelini** [comment]
Thinking a bit on how we can align `iree_codegen.ukernel.generic` with our tpp on tensor, and what we need to have in `iree_codegen.ukernel.generic`.

Single micro-kernel.

```
// TPP on tensor - no DPS
func.func @brgemm(%arg0: tensor<3x5x4xf32>, %arg1: tensor<3x4x5xf32>) -> tensor<5x5xf32> {
    %0 = tensor.empty() : tensor<5x5xf32>
    %1 = tpp.zero (%0) -> tensor<5x5xf32>
    %2 = tpp.brgemm (%arg0: tensor<3x5x4xf32>, %arg1: tensor<3x4x5xf32>, %1: tensor<5x5xf32>) -> tensor<5x5xf32>
    return %2 : tensor<5x5xf32>
}
```

```
// DPSfy and use ukernel.
func.fun @brgemm(%arg0: tensor<3x5x4xf32>, %arg1: tensor<3x4x5xf32>) -> tensor<5x5xf32> {
    %0 = tensor.empty() : tensor<5x5xf32>
    %flags = arith.constant 1024 : i32 // beta = 0
    %1 = iree_codegen.ukernel.generic "brgemm" ins(%arg0: tensor<3x5x4xf32>, %arg1: tensor<3x4x5xf32>)
                                               outs(%0: tensor<5x5xf32>) (%flags) -> tensor<5x5xf32>
    return %1 : tensor<5x5xf32>
}
```
```
// Bufferize
func.fun @brgemm(%arg0: memref<3x5x4xf32>, %arg1: memref<3x4x5xf32>) {
    %0 = memref.alloca() : memref<5x5xf32>
    %flags = arith.constant 1024 : i32 // beta = 0
    iree_codegen.ukernel.generic "brgemm" ins(%arg0: memref<3x5x4xf32>, %arg1: memref<3x4x5xf32>)
                                          outs(%0: memref<5x5xf32>) (%flags)
    return
}
```

```
// to func.
func.fun @brgemm(%arg0: memref<3x5x4xf32>, %arg1: memref<3x4x5xf32>) {
    %0 = memref.alloca() : memref<5x5xf32>
    %flags = arith.constant 1024 : i32
    /* some constants or dim for leading dims and sizes */
    %data_type = arith.constant 1 : i32
    %dispatch = call @xsmm_brgemm_dispatch(%data_type, .. leading dims + sizes + num batches) -> i64
    %ptr0 = memref.extract_metadata(%arg0).getBasePtr()
    %ptr1 = memref.extract_metadata(%arg1).getBasePtr()
    %ptr2 = memref.extract_metadata(%0).getBasePtr()
    call @xsmm_brgemm_invoke(%data_type, %dispatch, %ptr0, %offset0, %ptr1, %offset1, %ptr2, %offset2)
}
```

**With fusion**: C = unary_op(binary(unary(%arg0) * unary(%arg1 + C * beta), D))

```
func.func @brgemm_on_tensor(%arg0: tensor<3x5x4xf32>, %arg1: tensor<3x4x5xf32>) -> tensor<5x5xf32> {
    %0 = tensor.empty() : tensor<5x5xf32>
    %1 = tpp.zero (%0) -> tensor<5x5xf32>
    %2 = tpp.brgemm (%arg0: tensor<3x5x4xf32>, %arg1: tensor<3x4x5xf32>, %1: tensor<5x5xf32>) -> tensor<5x5xf32>
    %3 = tpp.add (%2: tensor<5x5xf32>, %cst: tensor<5xf32>) -> tensor<5x5xf32>
    %4 = tpp.relu (%3: tensor<5x5xf32>) -> tensor<5x5xf32>
    return %4 : tensor<5x5xf32>
}
```

```
func.fun @brgemm_on_tensor(%arg0: tensor<3x5x4xf32>, %arg1: tensor<3x4x5xf32>) -> tensor<5x5xf32> {
    %0 = tensor.empty() : tensor<5x5xf32>
    %flags = arith.constant 1024 : i32 // beta = 0
    %1 = iree_codegen.ukernel.generic "brgemm" ins(%arg0: tensor<3x5x4xf32>, %arg1: tensor<3x4x5xf32>, %0: tensor<5x5xf32>)
                                               outs(%0: tensor<5x5xf32>) (%flags) -> tensor<5x5xf32>
    %2 = tpp.add (%1: tensor<5x5xf32>, %cst: tensor<5xf32>) -> tensor<5x5xf32>
    %3 = tpp.relu (%2: tensor<5x5xf32>) -> tensor<5x5xf32>
    return %3 : tensor<5x5xf32>
}
```

```
attribute.descriptor {
    binary {
        operand_pos = 3
        type = ADD
        flags = BCAST_COL_OPERAND_1
    }
    unary {
        operand_pos = 2
        type = RELU
        flags = none
        when = POST
    }
}

func.fun @brgemm_on_tensor(%arg0: tensor<3x5x4xf32>, %arg1: tensor<3x4x5xf32>) -> tensor<5x5xf32> {
    %0 = tensor.empty() : tensor<5x5xf32>
    %flags = arith.constant 1024 : i32 // beta = 0
    %1 = iree_codegen.ukernel.generic "fused_brgemm" ins(%arg0: tensor<3x5x4xf32>, %arg1: tensor<3x4x5xf32>, %0: tensor<5x5xf32>, %cst: tensor<5xf32>)
                                                     outs(%0: tensor<5x5xf32>) (flags, #descriptor) -> tensor<5x5xf32>
    return %1 : tensor<5x5xf32>
}
```

Q1: Do we actually need M, N and K or can we materialize them during the lowering to func.call?
    If we let the user decide the lowering to callOp using the interface, can we avoid?
    `other_operands` is important for flags.
Q2: Drop tpp.group and use iree_codegen.ukernel.generic?

**Comment by rengolin** [comment]
As discussed, DPS is used by all other tensor dialects we use and is the preferred way they'll continue to be improved and new ones created, so we need to do the same. It doesn't matter how "it looks" in IR, just how we can use its semantics to generate good correct code.

Since we want to interoperate with the other dialects, including bufferization strategies across models with multiple dialects, we must use DPS like they do.

**Comment by chelini** [comment]
Please let's do not merge over the weekend. At least me or @adam-smnk should have reviewed it :)
Here my consideration:

Premise: I am fine switching to DPS, but I want to clarify my expectations.
Current documentation still misses details and is a bit open to interpretation.
So let' try to clarify. Also DPS has nothing to do with `tensor.empty`, which
seems another source of confusion.

Line 31, addition example:

```
  // Empty as out-of-place
  %C = tensor.empty : tensor <>
  %A = tpp.add ins(%arg0, %arg1) outs(%C) : (tensor<>, tensor<>) -> tensor<>
```

My interpretation of 'empty as out of place', may be wrong, so correct me if
this is the case, but I would assume the following bufferization:

```
  // Empty as out-of-place
  %C = memref.alloc()
  %A = tpp.add ins(%arg0, %arg1) outs(%C) : (memref<>, memref<>, memref<>)
```

Note:

1. We are giving our meaning to tensor.empty. The meaning of tensor empty at
   least in linalg is twofold: a) carry the shape or b) 'this is' the
   initialization buffer. Despite the fact that I don't like giving multiple
   meaning to ops, here we would add a third one: bufferize out-of-place if the
   `outs` is an empty.  Going back to linalg's meaning: If `tensor.empty` is used
   to carry the shape, I would claim the IR is way to verbose. We can get the
   shape from the result type, as we do today see below [1].  If `tensor.empty` is
   the initialization values we would change the semantics of the tpp.add, doing C
   += A + B instead of C = A + B. Bonus point of reading garbage memory. In
   The example, we have is broken if we apply the DPS rules (aka `outs`
   is the initialization tensor) as we read from a tensor.empty.

2. If tensor %arg0 and %arg1 have the same shape we could have avoided the
   allocation by reusing either %arg0 or %arg1.

Now let's assume we want to express the add in-place by *always* bufferize on
`outs`. We could think of writing something like:

```

%A = tpp.add ins(%arg0, %arg1) outs(%arg1) : (tensor<>, tensor<>) -> tensor<>

```

This to me is even worse than an allocation because we are basically taking
bufferization decision at the tensor level. For example, when mapping linalg to
tpp we need to decide the `outs`. It is unclear also what is the semantics of
`outs`. For `tpp.add` is the tensor we write to but for `tpp.gemm` is the
tensor we read from and write to.

For the example above line 31, the only use I see of tensor empty in the case
of `tpp.add` is to carry the shape of the result, but do we need it? We can
already specify it today. For example, we can write something like:

```
%0 = tpp.add(%arg0: tensor<3xf32>, %arg1: tensor<1x3xf32>) -> tensor<3x3xf32> [1]
```

The IR bufferize out-of-place, as:

```
%0 = memref.alloc() : memref<3x3xf32>
tpp.add ins(%arg0: memref<3xf32>, %arg1: memref<1x3xf32>) outs(%0: memref<3x3xf32>)
```

If we want to use DPS I would write the following IR:
```
%0 = tpp.add ins(%arg0: tensor<>) outs(%arg1: tensor<>) -> tensor<>
```

This IR is at least correct as now `outs` is not random memory. Here I am not
taking any stand on where we bufferize, this will be decided by our
bufferization. I may bufferize as memroy write to `ins` or `outs`. Overall if
we want to switch to DPS my proposal would be:

```
%0 = unary outs(%arg0: tensor<>) -> tensor<>
%1 = binary ins(%arg0: tensor<>) outs(%arg1: tensor<>) -> tensor<>
%2 = gemm ins(%arg0: tensor<>, %arg1: tensor<>) outs(%arg2: tensor<>) -> tensor<>
%3 = brgemm ins(%arg0: tensor<>, %arg1: tensor<>) outs(%arg2: tensor<>) -> tensor<>
```

**Comment by rengolin** [comment]
> Please let's do not merge over the weekend. At least me or @adam-smnk should have reviewed it :)

Sorry, from our sync, I thought we had consensus. The document change isn't meant to convey implementation details, only direction. The implementation details will be hashed our with the team as usual, but I wanted to make sure we avoid deviating from our main goal (running models efficiently) by experimenting with dialect syntax.

As we discussed before, we do what the other tensor dialects do because it's what works, not because it looks nice or is the best solution. Our research is not in dialect construction but hardware performance, so we need to focus.

> Premise: I am fine switching to DPS, but I want to clarify my expectations.

Ack. Just to be clear, don't read too much on the document. As before this change, it's not meant as implementation detail nor it's written in stone, but it conveys direction. I just reverted the original proposal' DPS syntax, nothing more.

> Overall if we want to switch to DPS my proposal would be:
> 
> ```
> %0 = unary outs(%arg0: tensor<>) -> tensor<>
> %1 = binary ins(%arg0: tensor<>) outs(%arg1: tensor<>) -> tensor<>
> %2 = gemm ins(%arg0: tensor<>, %arg1: tensor<>) outs(%arg2: tensor<>) -> tensor<>
> %3 = brgemm ins(%arg0: tensor<>, %arg1: tensor<>) outs(%arg2: tensor<>) -> tensor<>
> ```

We've been through this at the dungeon: we need ins and outs to show in/out place. Some unaries need to be out-of-place (transforms) while others can be in-place. Your proposal doesn't cover that. 

Let's not try to save characters in the text format and make everything explicit. One common syntax for all even if it has some redundances on the textual representation.

The syntax that is there is what we agreed before, all together, based on everyone's inputs. I'm trying to stop us from changing the syntax every two weeks.

**Comment by chelini** [comment]
> > Please let's do not merge over the weekend. At least me or @adam-smnk should have reviewed it :)
> 
> Sorry, from our sync, I thought we had consensus. The document change isn't meant to convey implementation details, only direction. The implementation details will be hashed our with the team as usual, but I wanted to make sure we avoid deviating from our main goal (running models efficiently) by experimenting with dialect syntax.

No problem, we all agree on the direction, but to get there, we need to implement something, and here, we have a rainbow of opinions. As far as I can remember, the syntax in the repo was discussed and agreed upon in Munich (https://github.com/plaidml/tpp-mlir/pull/457 and https://github.com/plaidml/tpp-mlir/commit/c756c5c27d20fd5b057c84859a0e4115fc957acd). Having broken documentation is also confusing; the example in line 31 cannot be DPS, and we may give people the wrong impression if we share documentation. We should give people the high-level story, but if we put more details (i.e., IR example), we need to make them consistent/correct with what we say. And provide good guidelines for who implements the dialect.

> 
> As we discussed before, we do what the other tensor dialects do because it's what works, not because it looks nice or is the best solution. Our research is not in dialect construction but hardware performance, so we need to focus.

Not all dialect tensor dialects implement DPS, and the fact that DPS may work for linalg does not guarantee it will work for TPP. I am happy to discuss why this is the case, but I encourage everyone to provide more concrete examples. Let's aim at having a discussion tomorrow or on Tuesday. 

> 
> > Premise: I am fine switching to DPS, but I want to clarify my expectations.
> 
> Ack. Just to be clear, don't read too much on the document. As before this change, it's not meant as implementation detail nor it's written in stone, but it conveys direction. I just reverted the original proposal' DPS syntax, nothing more.
> 
> > Overall if we want to switch to DPS my proposal would be:
> > ```
> > %0 = unary outs(%arg0: tensor<>) -> tensor<>
> > %1 = binary ins(%arg0: tensor<>) outs(%arg1: tensor<>) -> tensor<>
> > %2 = gemm ins(%arg0: tensor<>, %arg1: tensor<>) outs(%arg2: tensor<>) -> tensor<>
> > %3 = brgemm ins(%arg0: tensor<>, %arg1: tensor<>) outs(%arg2: tensor<>) -> tensor<>
> > ```
> 
> We've been through this at the dungeon: we need ins and outs to show in/out place. Some unaries need to be out-of-place (transforms) while others can be in-place. Your proposal doesn't cover that.

The DPS proposal should not cover how an op bufferize, and I am not proposing to switch; I suggest what I would do if we need to. 

> 
> Let's not try to save characters in the text format and make everything explicit. One common syntax for all even if it has some redundances on the textual representation.

This sentence is where there needs to be more clarification. In DPS, `outs` does not tell you if an operation bufferize in-place or out-of-place but tells you that `outs` is the initialization value. In Linalg, `outs` has the additional meaning of carrying just the shape of the result. If we attach DPS to TPP, the meaning of `outs` should be consistent with the interface. Bufferization decisions IMO should be taken later based on the conflicts you have and the operation semantics. If we want to attach a different meaning to `outs`, why do we need DPS?

> 
> The syntax that is there is what we agreed before, all together, based on everyone's inputs. I'm trying to stop us from changing the syntax every two weeks.

**Comment by adam-smnk** [comment]
> The DPS proposal should not cover how an op bufferize, and I am not proposing to switch; I suggest what I would do if we need to.

+1 - we can try to provide best effort hints in how we implement bufferization interface to promote in-place bufferization, however, DPS should not be used to force in-place concept that does not exist at tensor level.

> Not all dialect tensor dialects implement DPS

Any good examples? By that I mean something that is close to linalg like TPP dialect but does not use DPS.
IIUC, the main values for us in going DPS style are:
1) Enabling in-place bufferization with output into function arguments which is a common pattern.
2) (Easier?) Integration into other infrastructures that assume/require DPS format for ops - here it's a 'citation needed' moment but it could be needed for potential integration into IREE. Maybe @chelini has some examples if it is a real value or concern.

Overall, I think TPP fits DPS as captured in the posted proposal.

> Overall if we want to switch to DPS my proposal would be:
> 
> ```
> %0 = unary outs(%arg0: tensor<>) -> tensor<>
> %1 = binary ins(%arg0: tensor<>) outs(%arg1: tensor<>) -> tensor<>
> %2 = gemm ins(%arg0: tensor<>, %arg1: tensor<>) outs(%arg2: tensor<>) -> tensor<>
> %3 = brgemm ins(%arg0: tensor<>, %arg1: tensor<>) outs(%arg2: tensor<>) -> tensor<>
> ```

+1 - looks good to me.
For `tpp.zero`, `outs` is be 'shape only' but most cases `outs` have the 'init tensor' semantic.
Also, in general, we can write off passing `tensor.empty` into a `tpp.add` as UB.

**Comment by rengolin** [comment]
> The DPS proposal should not cover how an op bufferize, and I am not proposing to switch; I suggest what I would do if we need to.

This is even before we think about bufferization: What does `outs` mean here? Which one goes there? Does it even matter?
```mlir
%1 = binary ins(%arg0: tensor<>) outs(%arg1: tensor<>) -> tensor<>
```

In value semantics, this would have to be two `ins`. But value semantics doesn't work well with bufferization, so we have to take that into consideration.

You may claim the tensor design shouldn't care about bufferization, but it does, because this is how MLIR works now. It's not perfect, but it is what it is and we are not designing MLIR itself, and we are not researching how to change MLIR to separate bufferization from tensor dialect design. We're just using MLIR to generate optimal code.

**Comment by chelini** [comment]
> This is even before we think about bufferization: What does `outs` mean here? Which one goes there? Does it even matter?

If we adopt DPS interface `outs` has a precise meaning: it is the initialization tensor. In case of binary operations for us `outs` can be either `arg0` or `arg1`. We may bufferize over %arg1 or %arg0, it does not matter here.


> You may claim the tensor design shouldn't care about bufferization, but it does, because this is how MLIR works now. It's not perfect, but it is what it is and we are not designing MLIR itself, and we are not researching how to change MLIR to separate bufferization from tensor dialect design. We're just using MLIR to generate optimal code.

I am not claiming this at all. Instead, I am stating that DPS is only tangentially related to bufferization, and here we are mixing concepts. Again, I am not opposed to DPS, but I would like it if we aligned everyone's expectations by providing better design documents and examples. I still need help understanding your vision here. What is your idea of a TPP dialect using DPS, and how it connects to bufferization?

**Comment by chelini** [comment]
> Any good examples?

TCP dialect: https://github.com/llvm/torch-mlir/tree/mlir-tcp/externals/llvm-external-projects/torch-mlir-dialects/include/torch-mlir-dialects/Dialect/Tcp. And recently we are struggling a bit with DPS in `tensor.pack` as
we need to run analysis to understand if we can reuse the `outs` (https://github.com/llvm/llvm-project/blob/91cff8a71872cf49f0c5c9e5510f8065bfefa3c3/mlir/lib/Dialect/Linalg/Transforms/DataLayoutPropagation.cpp#L416).

**Comment by chelini** [comment]
> 2\. (Easier?) Integration into other infrastructures that assume/require DPS format for ops - here it's a 'citation needed' moment but it could be needed for potential integration into IREE. Maybe @chelini has some examples if it is a real value or concern.

I can try to find this answer at EuroLLVM, if some IREE folks are there. I don't have any "data point" on integrating in different framework.

**Comment by adam-smnk** [comment]
> If we adopt DPS interface outs has a precise meaning: it is the initialization tensor. In case of binary operations for us outs can be either arg0 or arg1. We may bufferize over %arg1 or %arg0, it does not matter here.

AFAIK, bufferization prefers `outs` whenever possible as the result destination at memref level. I believe this is the main point that @rengolin refers to. Although, it is technically bufferization implementation responsible for that not purely tensor semantic.

**Comment by adam-smnk** [comment]
> And recently we are struggling a bit with DPS in `tensor.pack` as we need to run dominance analysis to understand if we can reuse the `outs` (https://github.com/llvm/llvm-project/blob/91cff8a71872cf49f0c5c9e5510f8065bfefa3c3/mlir/lib/Dialect/Linalg/Transforms/DataLayoutPropagation.cpp#L416).

What's the semantic of non `tensor.empty` destination in case of `tensor.pack`? Is it done purely for bufferization purposes?

**Comment by chelini** [comment]
After discussing internally, we agree to keep the current custom bufferization. DPS provides a good guarantee on how the operand is bufferized, but we have a custom one; thus, we don't see the value currently. When and if we upstream TPP, we can reevaluate DPS on tensor.
