### ISSUE TITLE
Use `mlp-gen` for benchmarks

### ISSUE THREAD

**Issue by rengolin** [plaidml/tpp-mlir#533]
We're benchmarking a lot of matmul/fully-connected kernels, but we generated the MLIR files with some scripts / by hand, when we already have an MLP generator.

We should replace all (MLP-related) MLIR files in `benchmarks/mlir` with calls to `mlp-gen` with the appropriate flags, piping the result to `tpp-run`.

@adam-smnk

**Comment by adam-smnk** [comment]
We'll need to extend `mlp-gen` with ability to generate different kernel layouts e.g., MLP with constant weights, all buffers through args etc. Probably a few extra config flags should do the trick.

**Comment by rengolin** [comment]
That was the plan all along! :)
