### ISSUE TITLE
[RFC] `iree_codegen.ukernel.generic`

### ISSUE THREAD

**Issue by chelini** [plaidml/tpp-mlir#534]
We want to introduce a `ukernel.generic` op in MLIR that works both at tensor and memref, see: https://github.com/openxla/iree/issues/12300#issuecomment-1441311662

Op description: https://github.com/openxla/iree/blob/15121e89b21b047f9968ea7edc391a527437eb0d/compiler/src/iree/compiler/Codegen/Dialect/UKernelOps.td#L20

Plugin example in IREE: https://github.com/openxla/iree/tree/main/samples%2Fcustom_dispatch%2Fcpu%2Fplugin

Thinking a bit on how we can align `iree_codegen.ukernel.generic` with our tpp on tensor, and what we need to have in `iree_codegen.ukernel.generic`.

Single micro-kernel.

```
// TPP on tensor - no DPS
func.func @brgemm(%arg0: tensor<3x5x4xf32>, %arg1: tensor<3x4x5xf32>) -> tensor<5x5xf32> {
    %0 = tensor.empty() : tensor<5x5xf32>
    %1 = tpp.zero (%0) -> tensor<5x5xf32>
    %2 = tpp.brgemm (%arg0: tensor<3x5x4xf32>, %arg1: tensor<3x4x5xf32>, %1: tensor<5x5xf32>) -> tensor<5x5xf32>
    return %2 : tensor<5x5xf32>
}
```

```
// DPSfy and use ukernel.
func.fun @brgemm(%arg0: tensor<3x5x4xf32>, %arg1: tensor<3x4x5xf32>) -> tensor<5x5xf32> {
    %0 = tensor.empty() : tensor<5x5xf32>
    %flags = arith.constant 1024 : i32 // beta = 0
    %1 = iree_codegen.ukernel.generic "brgemm" ins(%arg0: tensor<3x5x4xf32>, %arg1: tensor<3x4x5xf32>)
                                               outs(%0: tensor<5x5xf32>) (%flags) -> tensor<5x5xf32>
    return %1 : tensor<5x5xf32>
}
```
```
// Bufferize
func.fun @brgemm(%arg0: memref<3x5x4xf32>, %arg1: memref<3x4x5xf32>) {
    %0 = memref.alloca() : memref<5x5xf32>
    %flags = arith.constant 1024 : i32 // beta = 0
    iree_codegen.ukernel.generic "brgemm" ins(%arg0: memref<3x5x4xf32>, %arg1: memref<3x4x5xf32>)
                                          outs(%0: memref<5x5xf32>) (%flags)
    return
}
```

```
// to func.
func.fun @brgemm(%arg0: memref<3x5x4xf32>, %arg1: memref<3x4x5xf32>) {
    %0 = memref.alloca() : memref<5x5xf32>
    %flags = arith.constant 1024 : i32
    /* some constants or dim for leading dims and sizes */
    %data_type = arith.constant 1 : i32
    %dispatch = call @xsmm_brgemm_dispatch(%data_type, .. leading dims + sizes + num batches) -> i64
    %ptr0 = memref.extract_metadata(%arg0).getBasePtr()
    %ptr1 = memref.extract_metadata(%arg1).getBasePtr()
    %ptr2 = memref.extract_metadata(%0).getBasePtr()
    call @xsmm_brgemm_invoke(%data_type, %dispatch, %ptr0, %offset0, %ptr1, %offset1, %ptr2, %offset2)
}
```

**With fusion**: C = unary_op(binary(unary(%arg0) * unary(%arg1) + C * beta, D))

```
func.func @brgemm_on_tensor(%arg0: tensor<3x5x4xf32>, %arg1: tensor<3x4x5xf32>) -> tensor<5x5xf32> {
    %0 = tensor.empty() : tensor<5x5xf32>
    %1 = tpp.zero (%0) -> tensor<5x5xf32>
    %2 = tpp.brgemm (%arg0: tensor<3x5x4xf32>, %arg1: tensor<3x4x5xf32>, %1: tensor<5x5xf32>) -> tensor<5x5xf32>
    %3 = tpp.add (%2: tensor<5x5xf32>, %cst: tensor<5xf32>) -> tensor<5x5xf32>
    %4 = tpp.relu (%3: tensor<5x5xf32>) -> tensor<5x5xf32>
    return %4 : tensor<5x5xf32>
}
```

```
func.fun @brgemm_on_tensor(%arg0: tensor<3x5x4xf32>, %arg1: tensor<3x4x5xf32>) -> tensor<5x5xf32> {
    %0 = tensor.empty() : tensor<5x5xf32>
    %flags = arith.constant 1024 : i32 // beta = 0
    %1 = iree_codegen.ukernel.generic "brgemm" ins(%arg0: tensor<3x5x4xf32>, %arg1: tensor<3x4x5xf32>, %0: tensor<5x5xf32>)
                                               outs(%0: tensor<5x5xf32>) (%flags) -> tensor<5x5xf32>
    %2 = tpp.add (%1: tensor<5x5xf32>, %cst: tensor<5xf32>) -> tensor<5x5xf32>
    %3 = tpp.relu (%2: tensor<5x5xf32>) -> tensor<5x5xf32>
    return %3 : tensor<5x5xf32>
}
```

```
attribute.descriptor {
    binary {
        operand_pos = 3
        type = ADD
        flags = BCAST_COL_OPERAND_1
    }
    unary {
        operand_pos = 2
        type = RELU
        flags = none
        when = POST
    }
}

func.fun @brgemm_on_tensor(%arg0: tensor<3x5x4xf32>, %arg1: tensor<3x4x5xf32>) -> tensor<5x5xf32> {
    %0 = tensor.empty() : tensor<5x5xf32>
    %flags = arith.constant 1024 : i32 // beta = 0
    %1 = iree_codegen.ukernel.generic "fused_brgemm" ins(%arg0: tensor<3x5x4xf32>, %arg1: tensor<3x4x5xf32>, %0: tensor<5x5xf32>, %cst: tensor<5xf32>)
                                                     outs(%0: tensor<5x5xf32>) (flags, #descriptor) -> tensor<5x5xf32>
    return %1 : tensor<5x5xf32>
}
```

Q1: Do we actually need M, N and K or can we materialize them during the lowering to func.call?
    If we let the user decide the lowering to callOp using the interface, can we avoid?
    `other_operands` is important for flags.
Q2: Drop tpp.group and use iree_codegen.ukernel.generic?

**Comment by chelini** [comment]
See also: https://github.com/openxla/iree/issues/12300#issuecomment-1441311662

**Comment by chelini** [comment]
@adam-smnk @rengolin @KavithaTipturMadhu @alheinecke

**Comment by rengolin** [comment]
IIUC, `vmvx` is similar to our TPP, and `ukernel` is similar to our `xsmm` dialect, right?

**Comment by chelini** [comment]
> IIUC, `vmvx` is similar to our TPP, and `ukernel` is similar to our `xsmm` dialect, right?

yes.

**Comment by rengolin** [comment]
> `ukernel` aims to be more generic. Basically it aims at representing micro kernel that can lower to func call.

Right, their xsmm level doesn't matter much to us. They have their own dispatch mechanism that are not meant to be the same as ours, or PyTorch, or Modular's new runtime. They're all different and we don't want to have to chose sides.

We can use our `xsmm` dialect to lower in `tpp-mlir` and they use `ukernel` in IREE. If they upstream their dialect, we can even later use it instead of `xsmm`, it's not a problem. We just need to make sure we give input so that it works for us, too.

What we do care about is the `tpp`  level, so `vmvx`. That needs to have strong semantics so we can do transformations on it. If it doesn't work at tensor level, then they need to fix the bufferization problems in `linalg`. But that's also not important.

What we need to do, as a team, is to look at their dialects, compare to ours, and give them a list of ideas from our experience, to improve their design, as well as take in their experience to improve our design. Once we reach a similar level of understanding, we can start working towards upstreaming those two dialects to MLIR.

If they start the upstreaming process before that, we need to make sure we give our feedback publicly and hopefully steer the design towards our use cases (if there's any problem).

We should not use IREE's dialects that are not upstream for the same reasons we couldn't have `linalg.brgemm` and `tensor.pack` in IREE and instead had to upstream it.

**Comment by rengolin** [comment]
> Q2: Drop tpp.group and use iree_codegen.ukernel.generic?

No, that's the wrong abstraction layer. We don't need another generic (we already have `linalg.generic`).

Also, we discussed on the dungeon that we don't want a single fusable operation for "all our GEMM purposes" to avoid having to encode the attributes like you did in the example. It doesn't scale.

If IREE folks have categorically decided against multiple semantic operations and grouping, we need to talk to them to understand why. We may be missing something. But if they haven't considered, then we need to talk to them anyway, to convey our conclusions and perhaps even change their minds.

**Comment by rengolin** [comment]
I'm closing this issue as it's not related to tpp-mlir directly today. We will not incorporate an IREE's (or any other framework's) dialect directly, only upstream dialects.

For the upstreaming discussions around `ukernel`, please use LLVM's official forum.

For the design of the dialect itself, please use IREE's mailing list or some other media.

For both cases, please include members of our team directly there.
