### ISSUE TITLE
Retire `QuarternaryOp` in XSMM

### ISSUE THREAD

**Issue by chelini** [plaidml/tpp-mlir#552]
We have in `XSMM` a quaternary operation to lower a `tpp.fused_brgemm` operation. As emerged in https://github.com/plaidml/tpp-mlir/commit/9f378036722368e8fc15f086089f6171c69914d2 it is better to have a custom dispatch call for brgemm, gemm. I like to retire this op and provide a custom dispatch op. 

Suggested syntax for dispatch:

```
%0 = xsmm.fused_brgemm.dispatch [13, 13, 13, 13, 13, 13] [add, relu]
    flags = (vnni_a) binary_flags = (bcast_col_in0) unary_flags = (none) data_type = bf16
```
1. `[13, 13, 13, 13, 13, 13] ` are leading dims and sizes.

2. ` [add, relu]` the fused unary and binary operations.

3. `flags = (vnni_a) binary_flags = (bcast_col_in0) unary_flags = (none)` are the flags for GEMM, binary (i.e., add) and unary (i..e, relu), respectively.

4. `data_type = bf16` is the data type.

The invoke will look like:

```
xsmm.fused_brgemm (data_type = f32, %arg0, %arg1, %arg2, %arg2)
    : (memref<2x2xf32>, memref<2x2xf32>, memref<2x2xf32>, memref<2x2xf32>) -> ()
```

It carries the data type and the memref to use.  It takes an extra memref compared to brgemm which is the bias to add.

It will connect to TPP via the `tpp.fused_brgemm` operation, recently updated in https://github.com/plaidml/tpp-mlir/pull/546. As an example,

```
func.func @fused_brgemm_tpp(%A: tensor<1x4x8xf32>,
                            %B: tensor<1x8x4xf32>, 
                            %C: tensor<4x4xf32>, %E: tensor<1x4xf32>) -> tensor<4x4xf32>  {
  %D = tpp.fused_brgemm [unary = none, binary = add] 
                        (%A: tensor<1x4x8xf32>, %B: tensor<1x8x4xf32>, 
                         %C: tensor<4x4xf32>, %E: tensor<1x4xf32>) -> tensor<4x4xf32>
  return %D: tensor<4x4xf32>
}
```
Will lower to a dispatch shown below:

```
%0 = xsmm.fused_brgemm.dispatch [4, 4, 8, 4, 4, 8] [add, none] flags = (none), binary_flags = (bcast_col_0), unary_flags = (none) data_type=f32
```

Suggested steps if we all agree:
1. Introduce the `xsmm.fused_brgemm.dispatch` and invoke. Retire the Quaternary op.
2. Connect `tpp_fused_brgemm` with XSMM by adding custom bufferization and conversion.

**Comment by rengolin** [comment]
The lowering is just to XSMM's similar function anyway, and this is in the `xsmm` dialect, not TPP, so I agree, this sounds much better than a generic quaternary.

As soon as we have a `tpp.group` op we cna retire the `tpp.fused_brgemm` but for now, connecting it to this xsmm op will do fine.

I agree with this direction. @adam-smnk @KavithaTipturMadhu opinions?

**Comment by KavithaTipturMadhu** [comment]
I agree with the custom dispatch approach in place of quarternary op.
