### ISSUE TITLE
Allocation in mobilebert

### ISSUE THREAD

**Issue by chelini** [plaidml/tpp-mlir#560]
```
%alloc_106 = memref.alloc() {alignment = 64 : i64} : memref<384x32xf32>
scf.forall () {
... write into %alloc_106
}
%alloc_112 = memref.alloc() {alignment = 64 : i64} : memref<1536x32xf32>
%subview_113 = memref.subview %alloc_112[0, 0] [384, 32] [1, 1] : memref<1536x32xf32> to memref<384x32xf32, strided<[32, 1]>>
memref.copy %alloc_106, %subview_113 : memref<384x32xf32> to memref<384x32xf32, strided<[32, 1]>>
```
We could avoid `alloc_106` by moving `%alloc_112` up and directly write into `subview_113`.

**Comment by rengolin** [comment]
What do you mean by avoid? Are we generating that code as part of our bufferization?

Please add the input IR and the steps necessary to reproduce the problem.

**Comment by chelini** [comment]
We could avoid the copies but adding a clean-up pass. We generate the allocation in the bufferization pass.

MobileBert: https://gist.github.com/chelini/d833f4a4e10a380c05043d05e387675c

Repro: `./tpp-opt mobilebert-linalg-stripped.mlir -linalg-fold-unit-extent-dims -tile-consumer-and-fuse-producers -rewrite-to-brgemm -convert-linalg-to-tpp -eliminate-empty-tensors -cse -bufferize="test-analysis-only print-conflicts"`

**Comment by rengolin** [comment]
What writes to the other subviews? I'm assuming it's the other "heads". If so, creating a cleanup for each "head" may lead to a "bubble-up" strategy (greedy-update-until-fix-point) which may work well.

We could also search for copies into subviews and if we find all producers of those origins, we just move the larger allocation past them all and replace all writes to subviews. This is a larger pass, but would be done once.

How do these play with packing? Hopefully the packing of all sub-tensors are identical to all sub-views, so that the matching remains valid.

**Comment by chelini** [comment]
> What writes to the other subviews?

Here the tensor pattern: https://gist.github.com/chelini/86ae2f1af8d489e938301fcbd4389fcc

**Comment by chelini** [comment]
Adding another pattern:

```
    %alloc_83 = memref.alloc() {alignment = 64 : i64} : memref<1x4x384xf32>
    linalg.fill ins(%cst_0 : f32) outs(%alloc_83 : memref<1x4x384xf32>)
    %subview_84 = memref.subview %alloc_83[0, 0, 0] [1, 4, 384] [1, 1, 1] : memref<1x4x384xf32> to memref<4x384xf32, strided<[384, 1]>>
    %alloc_85 = memref.alloc() {alignment = 64 : i64} : memref<4x384xf32>
    memref.copy %subview_84, %alloc_85 : memref<4x384xf32, strided<[384, 1]>> to memref<4x384xf32>
```

**Comment by rengolin** [comment]
> > What writes to the other subviews?
> 
> Here the tensor pattern: https://gist.github.com/chelini/86ae2f1af8d489e938301fcbd4389fcc

Right, as expected, it's the multiple heads writing to the whole tensor. I think we can find that pattern relatively easy and replace with writes to subviews.

> ```
>     %alloc_83 = memref.alloc() {alignment = 64 : i64} : memref<1x4x384xf32>
>     linalg.fill ins(%cst_0 : f32) outs(%alloc_83 : memref<1x4x384xf32>)
>     %subview_84 = memref.subview %alloc_83[0, 0, 0] [1, 4, 384] [1, 1, 1] : memref<1x4x384xf32> to memref<4x384xf32, strided<[384, 1]>>
>     %alloc_85 = memref.alloc() {alignment = 64 : i64} : memref<4x384xf32>
>     memref.copy %subview_84, %alloc_85 : memref<4x384xf32, strided<[384, 1]>> to memref<4x384xf32>
> ```

This one looks silly, similar to the previous ones we've seen of `alloc+alloc+copy` and could more generally be cleaned up.

**Comment by chelini** [comment]
Adding another pattern. This is DPS-style but the `inits` is not used in the body, thus the op can be in-place. Today it ends up in an allocation.
```
%0 = tensor.empty() : tensor<1x384xf32>
    %1 = linalg.generic {indexing_maps = [#map, #map], iterator_types = ["parallel", "parallel"]} ins(%arg1 : tensor<1x384xi32>) outs(%0 : tensor<1x384xf32>) {
    ^bb0(%in: i32, %out: f32):
      %4421 = arith.sitofp %in : i32 to f32
      linalg.yield %4421 : f32
    } -> tensor<1x384xf32>
```

**Comment by rengolin** [comment]
IIUC, many of these issues were fixed upstream. @chelini Is this still a problem?

**Comment by rengolin** [comment]
Closing as low importance and most allocation problems were fixed. We'll fix other problems as they come.
