### ISSUE TITLE
Recognize special addf+maxf fused linalg generic

### ISSUE THREAD

**Issue by rengolin** [plaidml/tpp-mlir#571]
In the past we approached the fused generic by trying to decompose it (#359, #339), but due to the complexities of identifying such cases and the fact that we're undoing fusion only to redo later on, we decided to go with a `tpp.group` operation that collects all scalar operations inside as a chain of operations on tiles.

However, `tpp.group` isn't going to be implemented soon and we now have a case of a matmul followed by bias add and relu (through IREE) that fuses the two element-wise ones too early, so when we lower to XSMM, we don't recognize their patterns.

Instead of reviving the decompose pass or rushing the implementation of `tpp.group` I propose special treatment for `addf+maxf` lowering to `tpp.add+tpp.relu`. Once `tpp.group` implementation can replace that lowering, we remove it from the code.

The rationale behind adding this _hack_ is that this is a key property of the main models we're working on and not recognizing them means half of our work goes down the drain, let alone performance crashing.

It should be trivial and isolated to have a post-TPP pass to recognize stray matches, which are all clear candidates for future cleaning.

**Comment by adam-smnk** [comment]
> It should be trivial and isolated to have a post-TPP pass to recognize stray matches, which are all clear candidates for future cleaning

Imo, this extra pattern detection can be part of the existing linalg to TPP conversion.

**Comment by rengolin** [comment]
Definitely could. We could even mark it as "future tpp.group detection" and convert it once we implement groups.
