### ISSUE TITLE
[RFC] How to represent DPS in current tensor TPP semantics

### ISSUE THREAD

**Issue by rengolin** [plaidml/tpp-mlir#575]
In #530 we discussed the pitfalls of not using DPS for our tensor semantics but there's a case where we might not have a choice.

While [working](https://github.com/rengolin/tpp-mlir/tree/fused-tpps) on #571 I got to the pattern (from #339):
```mlir
#map = affine_map<(d0, d1) -> (d0, d1)>
#map1 = affine_map<(d0, d1) -> (d1)>
module {
  func.func @linalg_bias_relu(%arg0: tensor<4x4xf32>,
                              %arg1: tensor<4xf32>,
                              %arg2: tensor<4x4xf32>) -> tensor<4x4xf32> {

    %cst = arith.constant 0.000000e+00 : f32

    %0 = linalg.generic 
              {indexing_maps = [#map, #map1, #map], iterator_types = ["parallel", "parallel"]}
              ins(%arg0, %arg1 : tensor<4x4xf32>, tensor<4xf32>)
              outs(%arg2 : tensor<4x4xf32>) {
    ^bb0(%in: f32, %in_0: f32, %out: f32):
      %1 = arith.addf %in, %in_0 : f32
      %2 = arith.maxf %1, %cst : f32
      linalg.yield %2 : f32
    } -> tensor<4x4xf32>

    return %0 : tensor<4x4xf32>
  }
}
```

Which is in DPS mode because linalg. The result needs to be in `%arg2`, which will be bufferized to output in that argument and the caller may expect to read from it.

When converting _just_ Relu, I can use `%arg2` directly (we have a test for this - in-place/out-of-place), which is fine. But with the Add, now there's a problem.

That IR I get is:
```mlir
module {
  func.func @linalg_bias_relu(%arg0: tensor<4x4xf32>, %arg1: tensor<4xf32>, %arg2: tensor<4x4xf32>) -> tensor<4x4xf32> {
    %0 = tpp.add (%arg0 : tensor<4x4xf32>, %arg1 : tensor<4xf32>) -> (tensor<4x4xf32>)
    %1 = tpp.relu (%0 : tensor<4x4xf32>) -> (tensor<4x4xf32>)
    return %1 : tensor<4x4xf32>
  }
}
```

which makes sense at tensor level, but has no indication that `%arg2` is involved in the calculation at all. Bufferization will (correctly) ignore that and just return the value.

If the IR did not have `%arg2`, this wouldn't be a problem. A "correct" tensor IR should not have it in the first place anyway.

So the question is: do we care about it, and change (again) the syntax to use DPS's `outs` or do we ignore this pattern (for now)?

@chelini @adam-smnk @KavithaTipturMadhu @hfp

**Comment by rengolin** [comment]
Just tried some in-line version...

From:
```mlir
#map = affine_map<(d0, d1) -> (d0, d1)>
#map1 = affine_map<(d0, d1) -> (d1)>
module {
  func.func @linalg_bias_relu(%arg0: tensor<4x4xf32>, %arg1: tensor<4xf32>, %arg2: tensor<4x4xf32>) -> tensor<4x4xf32> {
    %cst = arith.constant 0.000000e+00 : f32
    %0 = linalg.generic {indexing_maps = [#map, #map1, #map], iterator_types = ["parallel", "parallel"]} ins(%arg0, %arg1 : tensor<4x4xf32>, tensor<4xf32>) outs(%arg2 : tensor<4x4xf32>) {
    ^bb0(%in: f32, %in_0: f32, %out: f32):
      %1 = arith.addf %in, %in_0 : f32
      %2 = arith.maxf %1, %cst : f32
      linalg.yield %2 : f32
    } -> tensor<4x4xf32>
    return %0 : tensor<4x4xf32>
  }
}

// -----

#map = affine_map<(d0, d1) -> (d0, d1)>
#map1 = affine_map<(d0, d1) -> (d1)>
module {
  func.func @linalg_bias_relu(%arg0: tensor<4x4xf32>, %arg1: tensor<4xf32>) -> tensor<4x4xf32> {
    %cst = arith.constant 0.000000e+00 : f32
    %0 = linalg.generic {indexing_maps = [#map1, #map], iterator_types = ["parallel", "parallel"]} ins(%arg1 : tensor<4xf32>) outs(%arg0 : tensor<4x4xf32>) {
    ^bb0(%in: f32, %out: f32):
      %1 = arith.addf %in, %out : f32
      %2 = arith.maxf %1, %cst : f32
      linalg.yield %2 : f32
    } -> tensor<4x4xf32>
    return %0 : tensor<4x4xf32>
  }
}
```

To:
```mlir
module {
  func.func @linalg_bias_relu(%arg0: tensor<4x4xf32>, %arg1: tensor<4xf32>, %arg2: tensor<4x4xf32>) -> tensor<4x4xf32> {
    %0 = tpp.add (%arg0 : tensor<4x4xf32>, %arg1 : tensor<4xf32>) -> (tensor<4x4xf32>)
    %1 = tpp.relu (%0 : tensor<4x4xf32>) -> (tensor<4x4xf32>)
    return %1 : tensor<4x4xf32>
  }
}
// -----
module {
  func.func @linalg_bias_relu(%arg0: tensor<4x4xf32>, %arg1: tensor<4xf32>) -> tensor<4x4xf32> {
    %0 = tpp.add (%arg1 : tensor<4xf32>, %arg0 : tensor<4x4xf32>) -> (tensor<4x4xf32>)
    %1 = tpp.relu (%0 : tensor<4x4xf32>) -> (tensor<4x4xf32>)
    return %1 : tensor<4x4xf32>
  }
}
```

**Comment by adam-smnk** [comment]
IMO, based on the [High-Level Description of Linalg Ops](https://mlir.llvm.org/docs/Dialects/Linalg/):
`1. an “init tensor” output value which provides an initial value for a tensor that is created by iteratively updating the result (also called “destructive updates”). Such tensor is always materialized in some form. If enough fusion occurs it may end up being materialized only as a register-level SSA value. It is expected (but not required) that the destructive update pattern can be rewritten as an inplace update on buffers.`

we are free to ignore `%arg2` as its value is not being used by the original generic and we are free to bufferize it out of place.
However, what is concerning is that after split into tpps and bufferization, the `@linalg_bias_relu` function will end up storing its result in `%arg0`. We end up with a function that has unpredictable side effects depending on lowering path i.e., it modifies value of either `%arg0` or `%arg2`.

**Comment by rengolin** [comment]
> However, what is concerning is that after split into tpps and bufferization, the `@linalg_bias_relu` function will end up storing its result in `%arg0`. We end up with a function that has unpredictable side effects depending on lowering path i.e., it modifies value of either `%arg0` or `%arg2`.

Yup, my worries exactly.

**Comment by rengolin** [comment]
In theory, bufferization and reuse should not matter, just like register allocation. If all tensor ops had no DPS, this would be largely a lowering issue. There would never be an `%arg2` in the first place.

However, when interacting with (and lowering from) linalg, we have a cross-domain bufferization, which can generate not just unpredictable results, but incompatible results, such as writing to one buffer and reading from another on an originally clear DPS chain.

While we control our own bufferization, with cases like these, we'll lose information of the original chain, and will end up with multiple choices where originally there was only one. At bufferization, we will have no way of knowing what was the original choice and may pick the wrong one.

**Comment by chelini** [comment]
I wonder if the IR is a good example, I would have expected something like:

```
func.func @main(%arg0: tensor<4x4xf32>, %arg1: tensor<4x4xf32>) -> tensor<4x4xf32> {
  // now outs is used in the region.
  %0 = linalg.generic ins(%arg0: tensor<4x4xf32>) outs(%arg1: tensor<4x4xf32>) -> tensor<4x4xf32>
   return %0: tensor<4x4xf32>
}
```
In IREE they remove unused region args: https://github.com/openxla/iree/blob/aced620654d52092ed383d56cb1c6e153cd72ba9/compiler/src/iree/compiler/Codegen/Common/ConvertToDestinationPassingStylePass.cpp#L423

**Comment by rengolin** [comment]
Ok, I'll just assume "good IR" for now and we look again once we hit a broken case. Thanks!
