### ISSUE TITLE
Enforce code formatting on commit

### ISSUE THREAD

**Issue by adam-smnk** [plaidml/tpp-mlir#583]
We should enforce consistent code formatting to ensure smoother collaboration and reduce potential PR conflicts.
We already generally adhere to MLIR's clang-formatting rules. The formatting itself could be automated, for example, with git pre-commit hooks.

**Comment by rengolin** [comment]
The main problem here is that `clang-format` has no stability guarantees. Different OSs ship different clang versions which have their own `clang-format` and they all behave differently.

If I run `clang-format-9` on my code and you run `clang-format-12`, we'll get different results. If CI has `clang-format-14`, neither of us will "get it right" and CI will always fail.

In a [previous project](https://github.com/microsoft/ccf), we had a fixed version of `clang-format` that we all needed to use, a bash script that ran at CI and helped developers verify conformance before pushing, and a failing job in Github if the verification didn't pass (this is an easy Github action to have).

So, if we all agree on a specific version of `clang-format` and we make sure we all have a way to install/build one, I'd be happy to have a failing action to format code.
