### ISSUE TITLE
Robust Performance Benchmarks

### ISSUE THREAD

**Issue by rengolin** [plaidml/tpp-mlir#614]
Our current performance benchmarks are comprehensive, but the have a few issues:
1. Too many variations. We really only need a few representative shapes, not dozens.
2. OpenMP is noisy. We need to reduce the noise of the results somehow.
3. Sequential. One big job for all benchmarks means we can't run them in parallel.

To solve the **first** point, we should look at all the shapes, bundle them into groups and then pick one representative of each group. Hopefully we'll reduce to less than a dozen. We should also run them for longer, perhaps with a longer warm-up period and more layers. And given that fully connected layers have GEMMs in them, and that we'll rarely look at GEMMs into isolation, we could also just have FC benchmarks and measure our fusion skills, not just some raw numbers.

_To the future: we could re-introduce GEMM tests if we use them to compare to the FC numbers to show the Gflops loss due to fusion and optimise that gap._

To solve the **second** point, we need to understand where the noise it coming from. Choice of affinity parameters, not enough warm-up, unbalanced systems, some service running in the background, or just the way we run benchmarks (driver/dispatcher). If we can't get rid of some noise sources, we may have to run multiple times and pick a grouping strategy. This is a mechanical task, to make sure we get more reliable numbers, not a way to change the numbers themselves.

To solve the **third** point, we can just update the CI script to create multiple different jobs calling on different JSON files that can spawn on different nodes in parallel. This should be the easiest task in this list.

@adam-smnk @hfp

**Comment by hfp** [comment]
Regarding the **third** point, we have [this](https://github.com/libxsmm/libxsmm/tree/main/scripts#parallel-execution) in LIBXSMM to run tasks on a per-core/thread level (within the same reservation of a CI-instance).

**Comment by rengolin** [comment]
After we moved to the new cluster I made a few changes to the benchmarking infrastructure and is now much more stable and parallel.
