### ISSUE TITLE
Move our dep to stable libxsmm

### ISSUE THREAD

**Issue by rengolin** [plaidml/tpp-mlir#649]
We're using `main` that is unstable at the moment (for some definition), while `stable_main` is getting updates for ASIMD, SSE which we need. We can keep merging from `stable_main` into `main` but we really shouldn't. There is no reason why `tpp-mlir` needs to be on an unstable branch of libxsmm.

@hfp @alheinecke

**Comment by hfp** [comment]
We use more recent scripts from `main` (not backported to `main_stable`), and our performance reports will somewhat break when using `main_stable`. TPP-mlir uses no particular interface of LIBXSMM in question (or revised by `main`). Further, the term "stable" does mean an unstable implementation in `main` but rather stability to merge pending work/branches. The `main` branch has everything from `main_stable` but not the other way around.

**Comment by rengolin** [comment]
The main problem is people working on different branches with different commit policies.

As long as we're all working on the same branches with the same rules (PRs, tests, approvals) we know it's "stable enough" and we can close this issue.

**Comment by rengolin** [comment]
The `main` vs `main_stable` work has finished and now there's only one. But our current libxsmm hash is not just too old, it's from before the move. We just need to move to the new `main` and get this issue closed.

However, this also means fixing `libxsmm-dnn`'s issue https://github.com/libxsmm/libxsmm-dnn/issues/21 and our own issue #707 first.

**Comment by rengolin** [comment]
Apparently, just moving libxsmm to `main` worked without issues. We still have the warnings from #707 and libxsmm-dnn is still broken, but this issue here can be closed after #775.
