### ISSUE TITLE
XSMM fusion at memref level

### ISSUE THREAD

**Issue by rengolin** [plaidml/tpp-mlir#659]
While fusion at tensor level is easier due to SSA value tracking (easier to track def-use chains), it can be easily destroyed by bad bufferization. It also needs to know if the target will benefit from it or not, which needs a cost model at high level and the right path to memref to make it happen at the lower level.

We don't yet have a cost model, and MLIR's bufferization doesn't use anything like it, so even if we were to detect the costs at this high level, we'd be at the mercy of bufferization. Past experience is that some patterns work while others don't, so we're left with no choice but to fix bufferization problems after-the-fact (#658).

Regardless of the buffer problem above, we can already detect fusion at the XSMM level for the flags that XSMM supports. This isn't a generic logic, so should be done by XSMM code in XSMM dialect.

Example 1:
```mlir
  // From
  %0 = memref.alloc
  %1 = xsmm.unary zero(%0)
  %2 = xsmm.gemm(%arg0, %arg1, %1) // %1 is C

  // To
  %0 = memref.alloc
  %1 = xsmm.gemm(%arg0, %arg1, %0) { beta = 0 } // Beta(C) = 0
```

Example 2:
```mlir
  // From
  %0 = xsmm.gemm(...)
  %1 = xsmm.unary transpose(%0)
  %2 = xsmm.gemm(%arg0, %1, %arg2) // %1 a transposed argument

  // To either
  %0 = xsmm.gemm(...)
  %1 = xsmm.gemm(%arg0, %0, %arg2) { transpose_op = 1 }

  // Or
  %0 = xsmm.gemm(...) { transpose_result = true }
  %1 = xsmm.gemm(%arg0, %0, %arg2)
```

On both cases we need to look at `memref` semantics, so we need to look at the producer, list its consumers, make sure that the consumer pattern is the expected (usually just two: original op and the flag-bearing op), and then remove the flag op and add a flag to the correct op (producer or consumer, whatever is _"faster"_).

**Comment by chelini** [comment]
Addressed in: https://github.com/plaidml/tpp-mlir/commit/eeaea630de7d962e524e17017540ac8b990aad57
