### ISSUE TITLE
Update CUDA driver on the CI.

### ISSUE THREAD

**Issue by chelini** [plaidml/tpp-mlir#669]
This is needed for using newer LLVM version (see: #665 )
We use 11.5 but it does not have CUtensorMap. I found CUtensorMap in newer version (12.x).

**Comment by hfp** [comment]
This means upgrading all nvGPU nodes to CUDA 12.x (latest CUDA without limiting the general case). The latest version we have installed is v11.5. This must be done lockstep (cluster).

**Comment by hfp** [comment]
Completed per #670.
