### ISSUE TITLE
Investigate non scalability of OpenMP benchmarks in MLIR compiler

### ISSUE THREAD

**Issue by rengolin** [plaidml/tpp-mlir#734]
As exposed in #733, the MLIR OMP benchmarks don't scale at all, as if all of them are single-threaded. Must be some mistake on the flags side.

**Comment by rengolin** [comment]
The test `test/Integration/openmp/tpp-run-parallel.mlir` checks that OMP calls are made to an `scf.parallel`, and that is still working (test pass, I looked at the output, looks fine).

However, when running the same `tpp-run` command on the benchmarks, OMP calls are not made. Here's a reproducer:
```
$ tpp-run -def-parallel -e entry -entry-point-result=void -print-mlir=late benchmarks/mlir/mlp-fp32-3layers-1024.mlir
```

Expecting `omp.parallel`, `omp.wsloop`, `omp.yield`, `omp.terminator` but got `scf.forall`.

This was still working before #730, so I'm guessing this is related to upstream's change in `scf.parallel` to `scf.forall`.

@KavithaTipturMadhu, perhaps we need to recognize `scf.forall` for our OMP change?

**Comment by rengolin** [comment]
Hm, not so simple. The pass is [upstream](https://github.com/llvm/llvm-project/blob/ca003ee06d0eac7e8facc179181298a05e4d03ed/mlir/lib/Conversion/SCFToOpenMP/SCFToOpenMP.cpp#L358) and only works on `scf.parallel`.

Perhaps we should just not convert to `scf.forall` when using OpenMP? Or contribute to a rewriter for `scf.forall` upstream?

**Comment by chelini** [comment]
We could add back the pass `createConvertForAllToParallelOpPass` or contribute the pattern upstream.

**Comment by adam-smnk** [comment]
Looks like it's the same issue as with kernel outlining that it only expects `scf.parallel`.
We should add the conversion pass back for now.
Long term, upstream changes would be ideal.

**Comment by chelini** [comment]
mm, upstream seems ok: https://github.com/llvm/llvm-project/commit/87568ff3efb216e35161bf201897b2c587ffc1c4

**Comment by chelini** [comment]
I can take care of it tomorrow.

**Comment by rengolin** [comment]
> mm, upstream seems ok: [llvm/llvm-project@87568ff](https://github.com/llvm/llvm-project/commit/87568ff3efb216e35161bf201897b2c587ffc1c4)

Ah, I missed that one! Ok, perhaps we just need to add this pass before the OpenMP one and it'd work again. Thanks!
