### ISSUE TITLE
Verifier for GEMM and BRGEMM in XSMM

### ISSUE THREAD

**Issue by chelini** [plaidml/tpp-mlir#779]
We have 0 verifier for XSMM dialect. We should at least add them for GEMM and BRGEMM. 
What to check:
1. The first operands need to be an integer
2. Gemm and BRGEMM need to have three memref operands.
3. The last operand of a brgemm must be an integer (batch).

**Comment by rengolin** [comment]
See #581

**Comment by chelini** [comment]
Addressed in #810
