### ISSUE TITLE
`transform-convolutions.mlir` passes on my machine

### ISSUE THREAD

**Issue by rengolin** [plaidml/tpp-mlir#789]
As of today, the test `transform-convolutions.mlir` started passing on my machine, but it's marked as an XFAIL. `¯\_(ツ)_/¯`

There may be some instability that we need to root out here...

@chelini

**Comment by chelini** [comment]
The test was marked as XFAIL due to #769. I am still getting an error: `loc("<stdin>":101:5): error: memory free side-effect on MemRef value not supported! ERROR: Failed to lower IR to LLVM dialect`. You don't see any issue on your side?

**Comment by chelini** [comment]
LLVM: `bdac9720712a Fix load64_aligned (#71391)`

**Comment by rengolin** [comment]
> The test was marked as XFAIL due to #769. I am still getting an error: `loc("<stdin>":101:5): error: memory free side-effect on MemRef value not supported! ERROR: Failed to lower IR to LLVM dialect`. You don't see any issue on your side?

I don't get any error, so I can't compare. It's still XFAILing on the cluster, so CI is green, but that means the test is unstable.

Is that error expected to happen in the test you have? It's the same as @nhasabni had with the ownership based deallocation, so I'm surprised that this is what you wanted a year ago when the test was created.

If this isn't the error you're expecting, then the test has deviated from its original XFAIL criteria and I recommend we just remove it. You can keep it in a local branch until you craft it in a way that it fails for the reason you want it to fail, then push again.

**Comment by chelini** [comment]
> > The test was marked as XFAIL due to #769. I am still getting an error: `loc("<stdin>":101:5): error: memory free side-effect on MemRef value not supported! ERROR: Failed to lower IR to LLVM dialect`. You don't see any issue on your side?
> 
> I don't get any error, so I can't compare. It's still XFAILing on the cluster, so CI is green, but that means the test is unstable.
> 
> Is that error expected to happen in the test you have? It's the same as @nhasabni had with the ownership based deallocation, so I'm surprised that this is what you wanted a year ago when the test was created.
> 
> If this isn't the error you're expecting, then the test has deviated from its original XFAIL criteria and I recommend we just remove it. You can keep it in a local branch until you craft it in a way that it fails for the reason you want it to fail, then push again.

The test was disabled during the last llvm bump. I re-enabled it in #793

**Comment by adam-smnk** [comment]
It makes sense for the test to fail considering #769. The test also fails on CI and for me locally.
@rengolin how come you don't have the error? Are you running on different LLVM or tpp-mlir commits?

**Comment by rengolin** [comment]
> LLVM: `bdac9720712a Fix load64_aligned (#71391)`

That's the one I'm in.
