### ISSUE TITLE
Check Buildkite's Test Analytics

### ISSUE THREAD

**Issue by rengolin** [plaidml/tpp-mlir#792]
https://buildkite.com/test-analytics

If we dump the result of our benchmarks as JSON we don't need to parse them in the output, just upload to the test analytics and let the Buildkite UI's help us with the tracking.

Today we only print GigaFlops for each test, but as we start adding traces (see #788), we'll have a lot more data to cope with and text won't work anymore. We can still continue to print GigaFlops on the terminal, but we should also create a JSON file and upload it to the test analytics, so that we can properly track everything, including instructions, cache, TLB, branches, etc.

@alheinecke

**Comment by alheinecke** [comment]
What is the value of collecting instruction stats, cache misses, TLB stats and branch stats? Counter collection normally slows down executions and changes the behavior of the app. They only make sense on small regions (e.g. collection counters before and after a 10 layer MLP has close to no information --> means it doesn't tell you what is wrong). 
More over counter don't account for prefetches if one is not careful etc. 

I suggest fraction of peak in terms of GiB/s and GFLOPS is the best metric all the others we really have no handle on what to expect. 

So my questions here might be more about #788 and than this issue...

**Comment by rengolin** [comment]
> I suggest fraction of peak in terms of GiB/s and GFLOPS is the best metric all the others we really have no handle on what to expect.

Fair enough. Let's focus on GFlops for now

Looking at the test analytics, it is really only about pass/failure and timer history and sub spans. We'd have to treat each benchmark as a sub-benchmark of the whole thing, and pretend GF is "seconds" and pervert the UI to show us regressions in the wrong direction.
