### ISSUE TITLE
MHA benchmarks are taking too long

### ISSUE THREAD

**Issue by rengolin** [plaidml/tpp-mlir#805]
Most benchmarks we have run for seconds, but the MHA one is consistently over 6min. I'm not sure this is something in the compiler (some eager pass, or unoptimized constant folding) or the execution is really bad, but we need to solve that to be able to increase the number of iterations on weekly benchmarks consistently across the board.

@chelini

**Comment by rengolin** [comment]
All of them are fast enough, except `fp32-mha-tensorflow-seq-len-1024.mlir`. Each kernel runs for 5s on my machine, as opposed to 80ms for `fp32-mha-tensorflow-seq-len-32.mlir`. It's ~2% for both flops (141Gflops vs. 3.3Gflops) and time, so it's probably just a very big model that we could make smaller without breaking the objective of the test?

Maybe get sequence length = 128 would be a good compromise?

**Comment by rengolin** [comment]
I've disable the big one for now to run more of the rest of the benchmarks, we can re-enable it once we have a smaller version.

**Comment by chelini** [comment]
See: https://github.com/plaidml/tpp-mlir/commit/8cb9ca822edde668fe687b9c73e01e9e0d0d2496
